### ISSUE TITLE
Console errors after import

### ISSUE THREAD

**Issue by thebspin** [dbrizov/NaughtyAttributes#1]
Using Unity 2017.1.0p4 after importing my console is is filled with 6 times the same error:

NullReferenceException: Object reference not set to an instance of an object
UnityEditor.Scripting.ScriptCompilation.EditorCompilation.DirtyScript (System.String path) (at C:/buildslave/unity/build/Editor/Mono/Scripting/ScriptCompilation/EditorCompilation.cs:88)
UnityEditor.Scripting.ScriptCompilation.EditorCompilationInterface.DirtyScript (System.String path) (at C:/buildslave/unity/build/Editor/Mono/Scripting/ScriptCompilation/EditorCompilationInterface.cs:44)
UnityEditor.AssetDatabase:Refresh()
NaughtyAttributes.Editor.CodeGenerator:GenerateCode() (at Assets/NaughtyAttributes/Scripts/Editor/CodeGeneration/CodeGenerator.cs:36)

Also warnings about inconsistent line end, but that is easily fixeable. After clearing console it does work, just the warning comes up everytime opening the project.

**Comment by dbrizov** [comment]
Thanks mate. I will fix the line endings, but I really don't understand the NullReference.
It throws and exception at:
```
AssetDatabase.Refresh()
```
