### ISSUE TITLE
Draw ordering

### ISSUE THREAD

**Issue by OranBar** [dbrizov/NaughtyAttributes#10]
Hello.

I'd love a way to say: << Draw my fields below the upper class' ones >>

As in :

public class A{
    public int intField;
}

public class B{
    public string stringField;
}

Inspector
---------------
|  [__] intField      |
|  [__] stringField |
---------------
Is it possible?
I'm thinking maybe an attribute like [DrawInheritedFields], that you can place where-ever, and it will take into account its line position relative to the other attributes.

**Comment by dbrizov** [comment]
Hmm, I haven't tested that. The order is reversed really. I will try to fix it without any attributes mate. That is a wrong behavior.

**Comment by dbrizov** [comment]
I fixed the ordering mate. Everything is ordered depending on the class hierarchy now. Thank you very much for the issue report :)

**Comment by OranBar** [comment]
Cheers mate!
