### ISSUE TITLE
Inconsistent upm version and github releases

### ISSUE THREAD

**Issue by favoyang** [dbrizov/NaughtyAttributes#100]
Hi @dbrizov ,

Thanks for creating the upm branch to support the upm officially! However I found below problems

1) the inconsistent version string between GitHub release and upm branch
- https://github.com/dbrizov/NaughtyAttributes/releases version is 1.0.3
- the upm version is 1.0.0 https://github.com/dbrizov/NaughtyAttributes/blob/upm/package.json

2) Could you please make new GitHub release 1.0.4 **based on the upm branch** (and for all future releases). The benefits would be adding the version control for upm system. So that service like [OpenUPM](https://openupm.com) (a platform to pack GitHub releases into UPM packages) or https://github.com/mob-sakai/UpmGitExtension (a tool to manage upm with git), can resolve the GitHub releases as versions.

P.S. I'm the creator of OpenUPM.

3) A question, how you maintain the upm branch? It seems quite different from the master Assets/NaughtyAttributes, with folder moved manually. How you merge future changes from the master to the upm branch?

**Comment by dbrizov** [comment]
Hi @favoyang .

I am actually managing it in a very stupid way. Just like you said, the branch is completely different from the master. All the files were moved manually. I'll have a look at OpenUPM, looks very handy, and will save me the manual labor to maintain the upm branch.

**Comment by dbrizov** [comment]
Hi again @favoyang ,

I deleted all tags and releases and created a **1.0.0** release based on the **upm** branch. I tried adding the package to **OpenUPM** but @JimmyCushnie has already added a fork of it.
[https://openupm.com/packages/com.dbrizov.naughtyattributes/](https://openupm.com/packages/com.dbrizov.naughtyattributes/)
He states *"I won't be deleting this repo because people are using it in their projects and I don't want to break those. However, this fork will not be updated anymore. You should switch to the official repo.*"

Is it possible to reupload it, or just switch the URL?

**Comment by favoyang** [comment]
@dbrizov  As you're open to suggestion, I will proposal a way to help you sync the master to the upm branch (take some time to prepare the PR). And I will switch to this official repository once everything setup.

**Comment by favoyang** [comment]
@dbrizov see https://github.com/dbrizov/NaughtyAttributes/pull/101. The PR using CI (github action) to split an upm branch every time you push to master. It also restructure the folder to meet the upm standard. Please read the PR description to make sure you understand it. Feel free to ask me anything.

I also bump the package.json version to 1.0.4.

If you merge it, and everything goes right then please create GitHub release 1.0.4 later on.

**Comment by dbrizov** [comment]
@favoyang Thanks, I will do that now

**Comment by dbrizov** [comment]
@favoyang
Hey mate. It works like a charm. You did the heavy lifting. I actually learned a lot from you today. I didn't even know there was something like **git subtree** up until now. The **.github/workflows** with the **.yml** inside it is also new to me and it's amazing. Thank you very much

**Comment by favoyang** [comment]
@dbrizov 
Glad to know it works! I have switched to this official repository on the OpenUPM. And the 1.0.4 version has been processed successfully.  https://openupm.com/packages/com.dbrizov.naughtyattributes/

I also prepared PR #102 to update the docs.

**Comment by favoyang** [comment]
@dbrizov I write a blog about creating upm branch with CI - https://medium.com/openupm/how-to-maintain-upm-package-part-1-7b4daf88d4c4

**Comment by dbrizov** [comment]
@favoyang 
That's great. Thank you very much

**Comment by dbrizov** [comment]
@favoyang 
Hey mate, I just create a 2.0.0 release and it's not updated on the openupm registry. Does it need time to rebuild or something?

**Comment by favoyang** [comment]
Build pipelines scan whole list every 5mins. The build bot takes 1 minutes. So it takes 1-6 minutes to show up.

In future, we can make it better by creating an Github app to trigger on a release. But that will need package owners to install this app. While there are many things to do still, so this priority is low.
