### ISSUE TITLE
[Error] Unity CanvasGroup Error

### ISSUE THREAD

**Issue by MingFengShang** [dbrizov/NaughtyAttributes#108]
Change any parameter causes the following error

![image](https://user-images.githubusercontent.com/12228930/72790590-dc679100-3c70-11ea-9c72-37ef3e803249.png)

**Comment by dbrizov** [comment]
Will look at it when I get home

**Comment by dbrizov** [comment]
Fixed at 54e7a90

**Comment by MingFengShang** [comment]
nice！
