### ISSUE TITLE
No attribute working in some specific project

### ISSUE THREAD

**Issue by RicardoGuzmanVelasco** [dbrizov/NaughtyAttributes#109]
I've tried anything around clean installation, by package, importing today update in asset store... Nothing.
It's just in a project I'm working on. Maybe I'm missing something trivial? Sorry if that's the case.
It happens over all attributes and all scenes, event sample & test ones.
No default editor overloaded in such.

Of course it's working on others projects I've tested, as always.

**Comment by dbrizov** [comment]
It's just not working or there are exceptions? What Unity version are you using?

**Comment by dbrizov** [comment]
I am overriding the default Unity Inspector. If you have a custom inspector for all mono behaviors NaughtyAttributes is not going to work. The custom editor works on all `Unity.Object` objects. If you have a custom editor for `Unity.MonoBehaviour` - Unity will choose the one that is deeper in the class hierarchy tree. But I don't know if that's your case

![image](https://user-images.githubusercontent.com/3619573/72843155-9a574300-3ca2-11ea-82bd-eaf8f9531c68.png)

**Comment by dbrizov** [comment]
So the ScriptableObjectFoldoutTool is overring the editor?
I actually have a feature request for implementing such a feature.
