### ISSUE TITLE
[ReadOnly] does not work on ScriptableObjects in NaughtyAttributes 2.x, used to in 1.x.

### ISSUE THREAD

**Issue by KesKim** [dbrizov/NaughtyAttributes#113]
I have a couple of ScriptableObjects where the [ReadOnly] attribute was handy for some ScriptableObjects, blocking user intereference with some fields I only wanted to view for debug in the Inspector when selecting these ScriptableObject Assets.

After upgrading to 2.0.1, the [ReadOnly] no longer does anything to disable the fields as it used to.

Both versions 1.0.3 and 2.0.1 of NaughtyAttributes tested in Unity 2019.3.0f5.

**Comment by dbrizov** [comment]
Just tested it in Unity **2019.3.0f6** and **2019.2.17f2**, and it's working. Check if you have other plugins overriding the inspector.

![image](https://user-images.githubusercontent.com/3619573/73748314-ce7e3980-4761-11ea-866b-448302b1204f.png)

**Comment by KesKim** [comment]
Must be my mistake - you are correct; I didn't account to the possibility of us changing the type of the field at some point in between the version changes and it does seems like it's a [System.Serializeable] type class with a CustomInspector of its own.

And I just found your main page documentation on this:

> Most of the attributes are implemented using Unity's CustomPropertyDrawer, so they will work in your custom editors. If you want all of the attributes to work in your custom editors, however, you must inherit from NaughtyInspector and use the NaughtyEditorGUI.PropertyField_Layout function instead of EditorGUILayout.PropertyField.

I'll test this right away!

**Comment by KesKim** [comment]
Wait, does that workflow even apply for [CustomPropertyDrawer]s in Editor/ folders? The CustomPropertyDrawer I have seems unable to reference NaughtyAttributes namespace, and it's inheriting from UnityEditor.PropertyDrawer not Editor so even if I could reference it, NaughtyInspector/UnityEditor.Editor would not be a suitable replacement.

Any suggestions?

**Comment by dbrizov** [comment]
You have an **Editor** or a **CustomPropertyDrawer** for your scriptable object?

**Comment by KesKim** [comment]
> 
> 
> You have an **Editor** or a **CustomPropertyDrawer** for your scriptable object?

CustomPropertyDrawer.

**Comment by dbrizov** [comment]
In that case **[ReadOnly]** should work. I need to investigate this.

**Comment by dbrizov** [comment]
Do you apply the **[ReadOnly]** attribute to the **ScriptableObject** property, or you are using the **[ReadOnly]** attribute for the properties inside the **ScriptableObject**?

**Comment by KesKim** [comment]
Apologies, I seem to be changing the description constantly - I'm getting mixed up in changes in our codebase. I realise that must've wasted some of your time since I can't now find the CustomPropertyDrawer issue examples I was talking about... It seems to be a List<string> and one List<X> where X is a System.Serializable class, and that List<X> is in a ScriptableObject.

I'm trying to double-check and clarify here now. [ReadOnly]+[CustomPropertyDrawer] DO seem to work. Again, my apologies for the hassle. Some examples that don't seem to work with [ReadOnly]:

Case, List<string> on ScriptableObject
`    public class BootConfigurationManager : ScriptableObject
    {
        [ReadOnly]
        // ReadOnly works correctly (BootConfiguration is another ScriptableObject)
        public BootConfiguration ActiveConfiguration;

        [ReadOnly]
        // ReadOnly does not seem to work
        [SerializeField] private List<string> EditModeScenePaths;`

Another case, List<System.Serializable class> on ScriptableObject:

`public class SceneList : ScriptableObject
    {
        [ReadOnly]
        // ReadOnly doesn't work
        public List<RuntimeSceneInfo> ScenesInBuild;`

So it seems to be List<T> that is the issue, not what I panicked about initially.

**Comment by KesKim** [comment]
Aaand further than that - seems the issue was only troubling where I was looking at EMPTY Lists!
The Size/Count Inspector field is editable on [ReadOnly] Lists, which caused me to think the Lists can be modified via Inspector (which they can, since the Size-field can delete or add entries which is undesired if the List is ReadOnly).

**Comment by dbrizov** [comment]
Unity works a little strangely. In the case of a list, the **CustomPropertyDrawer** actually applies the attribute for each element of the list, not the list itself.

![image](https://user-images.githubusercontent.com/3619573/73753267-181f5200-476b-11ea-9a70-681addda4433.png)
