### ISSUE TITLE
Button, ResizableTextArea, ReorderableList, ShowNativePropertyTest ShowNonSerializedFieldTest, BoxGroup, EnableIf, ShowIfTest, Label, OnValueChanged, MinValue, MaxValue, Required, ValidateInput not working in Unity 2019.3.0f6

### ISSUE THREAD

**Issue by ufodriverr** [dbrizov/NaughtyAttributes#119]
1st I want to thank you a lot for this tool. It's awesome, using it for a long time now =)

![image](https://user-images.githubusercontent.com/7818629/74435536-edb54f00-4e64-11ea-8897-29ebbaa96b8c.png)
Button, ResizableTextArea, ReorderableList, ShowNativePropertyTest ShowNonSerializedFieldTest, BoxGroup, EnableIf, ShowIfTest, Label, OnValueChanged, MinValue, MaxValue, Required, ValidateInput  not working in Unity 2019.3.0f6 

Downloaded form AssetStore

**Comment by dbrizov** [comment]
I am with the same version and it's working on my end. Do you have any other plugins that may interfere with the Unity Inspector? 

![image](https://user-images.githubusercontent.com/3619573/74605468-0aee5580-50d1-11ea-86fb-fdd71704d570.png)

**Comment by andre-uncloudy** [comment]
I also have this issue and I'm on 2019.3.0f6.
@ufodriverr Did you manage to solve it?

**Comment by ufodriverr** [comment]
Nope. Still have this issue =)

**Comment by andre-uncloudy** [comment]
@ufodriverr That's a shame, thanks anyway :)
