### ISSUE TITLE
NullReferenceException - For removed scripts

### ISSUE THREAD

**Issue by ralofpatel** [dbrizov/NaughtyAttributes#120]
This error is produced when any component is not loaded in the Inspector of any object. This can happen when the script file for the component is deleted. Maybe null check can prevent this from spamming Console with NullExceptionErrors.  And one more thing: NaughtyAttributes 2 is da Best.
The error happens at following line as per the Unity console:

`public static class ReflectionUtility
	{
		public static IEnumerable<FieldInfo> GetAllFields(object target, Func<FieldInfo, bool> predicate)
		{
			List<Type> types = new List<Type>()   ////   <<<<< At this line
			{
				target.GetType()
			};`

**Comment by ralofpatel** [comment]
Also, In my case I actually didn't delete the component script file but I renamed it in the Project view but the class name was not updated in the script file so the component was not being loaded in the Inspector.

**Comment by dbrizov** [comment]
Same as #161
