### ISSUE TITLE
Asset files with ScriptableObjects are editable?

### ISSUE THREAD

**Issue by RobTranquillo** [dbrizov/NaughtyAttributes#121]
I stumble a bit when using ScriptableObjects in the AssetDatabase. I have very complex ScriptableObjects that are stored as assets in the AssetDatabase. These are dragged onto a GameObject and evaluated at runtime.
So far I have edited the assets with the UnityEditor, but I would like to edit them more comfortable. Until now, I could not find a way to manage this with NaughtyAttributes.

If tags like "[ReorderableList]" are used in the ScriptableObject, Unity will only show the default property drawer for it.

I can imagine that I would have to create member variables in the script on the GameObject, in which the ScriptableObject is linked, which would have to get the values from the ScriptableObject somehow. But first of all I don't want to know the inner structure of the ScriptableObjects. And second, I don't know how the values from the GameObject should be written back into the ScriptableObject.

Do you think that's possible and can you help me?
Thank you very much.

**Comment by dbrizov** [comment]
I don't quite understand your question mate. Can you give me an example of what exactly you are trying to do?

**Comment by RobTranquillo** [comment]
Thank you for your answer. I solved the problem.
