### ISSUE TITLE
[Issue] ReorderableList makes Inspector ignore Header & Space attributes

### ISSUE THREAD

**Issue by orangy** [dbrizov/NaughtyAttributes#126]
If I place additional attributes on to the field with `[ReorderableList]`, they are ignored:

```
        [Space]
        [ReorderableList]
        public List<EffectBase> collisionEffects;
```

**Comment by dbrizov** [comment]
This is duplicates #16
Also, since Unity **2020.2.x** all lists are reorderable by default. You don't have to use NA'a ReorderableList attribute anymore. The Space and Header attributes should be workling fine
