### ISSUE TITLE
Buttons not showing?

### ISSUE THREAD

**Issue by LukeSeers** [dbrizov/NaughtyAttributes#136]
I have been trying to figure this out for the past couple of hours and I'm not getting anywhere. 

I have imported **NaughtyAttributes** from the **Asset Store** and also tried from **Github**, 

_Unity3D: 2019.3.3f1_
_NaughtyAttributes: 2.0.3_

I've attach this script to a empty GameObject in a empty scene: (I've also tested it out in the **NaughtyAttributes** test scene and the button still don't show)

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using NaughtyAttributes;

public class DataController : MonoBehaviour
{
    [Button]
    public void PleaseWork() { }
}
```

I don't know if I'm missing a key bit of information.

**Comment by dbrizov** [comment]
Do you have any custom editors that might be overriding NaughtyAttributes?

**Comment by LukeSeers** [comment]
**Do you have any custom editors that might be overriding NaughtyAttributes?**
Yes

I noticed this in the docs a while back when I first was looking into **NaughtyAttributes**:

> If you want all of the attributes to work in your custom editors, however, you must inherit from NaughtyInspector and use the NaughtyEditorGUI.PropertyField_Layout function instead of EditorGUILayout.PropertyField

Since I have not mess around with the whole custom Unity Editor thing, I have no clue. I know this might be a hacky way, but is there away to just override everything?

**Comment by LukeSeers** [comment]
Right, I've got it working. Thank you for your help mate!

**Comment by dbrizov** [comment]
What was the issue?

**Comment by LukeSeers** [comment]
I had a couple of assets which was overriding **NaughtyAttributes**. Since I was just playing around with them I just removed them. 

If you want to recreate the issue I was having here are the assets I was using **(I would like to add that it was one of these, I don't know if it was both causing the issue)**:

https://assetstore.unity.com/packages/vfx/shaders/free-skybox-extended-shader-107400
https://assetstore.unity.com/packages/tools/modeling/splinemesh-104989
