### ISSUE TITLE
Where can I donate?

### ISSUE THREAD

**Issue by LukeSeers** [dbrizov/NaughtyAttributes#137]
What can I say, I love **NaughtyAttributes** it's very light weight and not to mention it's free and open source. Where can I donate? it wont be a lot, but it's something that you can treat yourself with 🙂

@dbrizov Keep up the great work mate!

**Comment by dbrizov** [comment]
Thanks mate. If you want to donate you can check the README. I will mark this closed, because it's not an issue :)

**Comment by LukeSeers** [comment]
How did I miss that.. Sorry for making a ticket facepalm*
