### ISSUE TITLE
Showif/Hideif/EnableIf/DisableIf  not working , Only with Vector2

### ISSUE THREAD

**Issue by arnesso** [dbrizov/NaughtyAttributes#139]
These functions dont work properly.  It works onyl if I use [minmaxslider] AND Vector2 
Any other case the variables are always shown,enabled  in the inspector 
I tried with unity 2019.3.4,  and 2019.3.1f1

**Comment by dbrizov** [comment]
Can you show me the exact code? Are you by any chance using them in nested classes?
If so you need to check the [AllowNesting](https://dbrizov.github.io/na-docs/attributes/special_attributes/allow_nesting.html) attribute.

**Comment by arnesso** [comment]
Nothing special  in the code, I used it many times.  No i don't use it
Nested classes.
This is only the second project,where it does not work, any other cases it
works well.
I just don't know what can cause this problem. ( I tried reimport, too)
Thank you fro your response. have a nice day!
[image: image.png]

Denis Rizov <notifications@github.com> ezt írta (időpont: 2020. márc. 11.,
Sze, 18:49):

**Comment by dbrizov** [comment]
Probably some other plugin you are using is overriding the inspector.
> Most of the attributes are implemented using Unity’s CustomPropertyDrawer, so they will work in your custom editors. If you want all of the attributes to work in your custom editors, however, you must inherit from NaughtyInspector and use the NaughtyEditorGUI.PropertyField_Layout function instead of EditorGUILayout.PropertyField.
