### ISSUE TITLE
Button at the bottom of the inspector

### ISSUE THREAD

**Issue by Shinao** [dbrizov/NaughtyAttributes#14]
The button attribute gets taken to the bottom of the inspector ignoring the class hierarchy.
It does not make sense when you group attributes together but your button is not with them.

Great repo though :)

**Comment by dbrizov** [comment]
Yeah you are right. I will fix. I have a lot to fix actually. I am very
busy these days, and don't have time to spare. In a week I will have some
free time to fix the issues. Thanks for the feedback

**Comment by beardordie** [comment]
I'm recommending this repo for those who don't want to or cannot purchase Odin. It does quite a lot of the things that I use Odin for on a regular basis. Wonderful that it is free. Thanks.

**Comment by Shinao** [comment]
That's exactly what I'm using it for.
My problem with Odin is that it slows my editor quite a bit and you cannot share your projects with it since it's closed source.
If you have a bit of time to add the attribute/drawers that you find useful to this project and do a PR that would be great.

**Comment by Shinao** [comment]
Is there an ETA on this problem ?

**Comment by dbrizov** [comment]
Sorry, but I really don't have time these days. We are very busy at the
office, and I don't have much time to spare. I will do something about it
when I can.

**Comment by Shinao** [comment]
Alright, I will try to get around this problem in the meantime, thanks for the reply.

**Comment by Shinao** [comment]
Any updates ?

**Comment by wagenheimer** [comment]
Any updates on this?

**Comment by dbrizov** [comment]
I reworked the entire project and decided that this is by design. First the serialized properties are drawn, then the non-serialized fields, then the native C# properties and then the methods. They are now separated by horizontal lines so you can very easily see what is what.

**Comment by JimmyCushnie** [comment]
> They are now separated by horizontal lines so you can very easily see what is what.

That sounds excellent, I can't wait to try version 2!
