### ISSUE TITLE
[Issue] NullReferenceException on [ShowNativeProperty]

### ISSUE THREAD

**Issue by pippinmole** [dbrizov/NaughtyAttributes#140]
![image](https://user-images.githubusercontent.com/40035529/76451948-2eeb4100-63c8-11ea-9186-7288c88adc4c.png)

![image](https://user-images.githubusercontent.com/40035529/76451965-3579b880-63c8-11ea-93b7-93ecc8f5d49b.png)

If one of those property chains is null, it throws an error in editor (not playing the game).

**Comment by dbrizov** [comment]
Thank you very much mate, I will investigate.

**Comment by dbrizov** [comment]
Mate, I can't do anything to fix it. I can't detect a null object inside the property chain.
What you can do to prevent it is to just safeguard the chain.
Instead of `FirstProp.SecondProp.ThirdProp` you can do `FirstProp?.SecondProp?.ThirdProp` and that fixes it.
