### ISSUE TITLE
[Request] (show/hide/enable/disable)if Enum

### ISSUE THREAD

**Issue by android272** [dbrizov/NaughtyAttributes#141]
It would be very nice if you could showif / hideif / enableif / disableif fields of other types are set to something. I currently have the need to show/hide inspector fields depending on an Enum dropdown. I really like the fact that your attributes have the ability to string multiple conditions together with the and or statements but it would be even better if bools were not the only thing I could check.

**Comment by dbrizov** [comment]
You can. The condition can be any boolean `field`, `property`, or `function`. Just make a function `DoesEnumHasSomeValue`

**Comment by android272** [comment]
Also, how do you even use Naughty Attributes? When I add your attributes to my classes Unity throws the error:

`Assets\Scripts\xNode\RoomDescription.cs(17,9): error CS0246: The type or namespace name 'ShowIfAttribute' could not be found (are you missing a using directive or an assembly reference?)`

But when adding `using NaughtyAttributes` I get this error:

`Assets\Scripts\xNode\RoomDescription.cs(5,7): error CS0246: The type or namespace name 'NaughtyAttributes' could not be found (are you missing a using directive or an assembly reference?)`

How do I use your attributes? Did I miss spell the using?

**Comment by dbrizov** [comment]
Reimport the plugin, delete your Library folder.
Don't know that the problem is.

**Comment by Cdddo** [comment]
@android272 if you are using assembly definitions, then you need to add the NaughtyAttributes reference.
