### ISSUE TITLE
[ShowIf] not working on class objects on ScriptableObject

### ISSUE THREAD

**Issue by pippinmole** [dbrizov/NaughtyAttributes#149]
https://pastebin.com/jb3fzYSM
https://gyazo.com/3aba3433d0a13d01034d856375427597

No errors/warning messages are shown.

Thanks

**Comment by dbrizov** [comment]
You need to flag it with the [[AllowNesting]](https://dbrizov.github.io/na-docs/attributes/special_attributes/allow_nesting.html) attribute.

**Comment by pippinmole** [comment]
Ah thank you
