### ISSUE TITLE
[Required] tag not being ordered properly when using [AllowNesting]

### ISSUE THREAD

**Issue by pippinmole** [dbrizov/NaughtyAttributes#150]
![image](https://user-images.githubusercontent.com/40035529/77837411-0ce01580-7161-11ea-8025-3092b5610bbd.png)
produces this result
![image](https://user-images.githubusercontent.com/40035529/77837413-136e8d00-7161-11ea-8b25-2f444082b1b4.png)

it should be under 'Item Template'

**Comment by dbrizov** [comment]
duplicate of #124
