### ISSUE TITLE
[Request] Enable use of [Button] on coroutines

### ISSUE THREAD

**Issue by JimmyCushnie** [dbrizov/NaughtyAttributes#151]
You should be able to use [Button] on an IEnumerator, which would start that as a coroutine on the component the button is attached to.

**Comment by garrafote** [comment]
@JimmyCushnie I did a bunch of enhancements on the Button attribute on my pull request #152. Went ahead and also added coroutine support as you requested.

Hope you like it :)

**Comment by JimmyCushnie** [comment]
Looks fantastic! Thank you very much!

**Comment by dbrizov** [comment]
Cherry picked the coroutine support from #152
The button attribute can also be used on methods with default parameters.
Here is the commit: 0ac04b559f931705e6053eb73d5f35592b361af4
The change is still only on the **v2** branch

**Comment by JimmyCushnie** [comment]
> The button attribute can also be used on methods with default parameters.

That's amazing. Thank you for all your hard work on NaughtyAttributes ♥

**Comment by dbrizov** [comment]
> > The button attribute can also be used on methods with default parameters.
> 
> That's amazing. Thank you for all your hard work on NaughtyAttributes ❤

@garrafote also implemented that, I just merged it :)
