### ISSUE TITLE
[Button] doesn't work in abstract classes 

### ISSUE THREAD

**Issue by pippinmole** [dbrizov/NaughtyAttributes#153]
![image](https://user-images.githubusercontent.com/40035529/78254200-75c2e700-74ed-11ea-8d12-342bc73d0222.png)

When i deploy a WeaponControllerMelee : WeaponController, it does not show up in inspector.
![image](https://user-images.githubusercontent.com/40035529/78254266-925f1f00-74ed-11ea-81dc-32170897666f.png)

**Comment by uniquecorn** [comment]
set the method to protected? your melee class cannot see the method and therefore cannot display it

**Comment by pippinmole** [comment]
> 
> 
> set the method to protected? your melee class cannot see the method and therefore cannot display it

Oh cheers - stupid mistake on my behalf :P
