### ISSUE TITLE
Issue when upgrading to 2019.3.12f1

### ISSUE THREAD

**Issue by Sneox20** [dbrizov/NaughtyAttributes#159]
Hi, I've got an issue when updating my project (where NaughtyAttributes is installed) from 2019.3.10f1 to 2019.3.12f1 this issue is that when I type on my script " using NaughtyAttributes " it is like it isn't installed.
![image](https://user-images.githubusercontent.com/49684707/80843013-72fa0580-8c03-11ea-9bb8-4a770beace56.png)

But what is very strange is that when I look at my inspector, the package is working successfully!
On my screenshot, you may see BoxGroups
![image](https://user-images.githubusercontent.com/49684707/80843638-13045e80-8c05-11ea-8575-89e22aac0b32.png)

Of course, I may live that error anyway but because of that issue... I got so many errors and it bothers me because I'd like to correct every errors I may find in my scripts.
![image](https://user-images.githubusercontent.com/49684707/80843825-81e1b780-8c05-11ea-9dc4-5a781f0aa917.png)

By the way, once I did downgrade to 3.10f1 everything now works as if nothing happened.
Thank you if you could help me with it.

**Comment by dbrizov** [comment]
I just updated to **2019.3.12f1**, and it's the same on my end. I deleted all VS files (*.sln, *.csproj, .vs), and regenerated them again. Deleted the Library folder. Nothing works. I don't know what causes this. The only thing I can do right now is to wait for **2019.3.13f1**. I rolled back to **2019.3.11f1**, and it's fine. Stick to an alder version in the meantime.

**Comment by dbrizov** [comment]
Just tested it on Unity **2019.4.f1 LTS**, and everything is ok.
