### ISSUE TITLE
Null reference if viewing a gameobject with null script

### ISSUE THREAD

**Issue by pippinmole** [dbrizov/NaughtyAttributes#161]
`NullReferenceException: Object reference not set to an instance of an object
NaughtyAttributes.Editor.ReflectionUtility+<GetAllFields>d__0.MoveNext () (at Assets/Decay.Utilities/NaughtyAttributes/Editor/Utility/ReflectionUtility.cs:12)
System.Linq.Enumerable.TryGetFirst[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Boolean& found) (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
System.Linq.Enumerable.FirstOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source) (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
NaughtyAttributes.Editor.ReflectionUtility.GetField (System.Object target, System.String fieldName) (at Assets/Decay.Utilities/NaughtyAttributes/Editor/Utility/ReflectionUtility.cs:71)
NaughtyAttributes.Editor.PropertyUtility.GetAttributes[T] (UnityEditor.SerializedProperty property) (at Assets/Decay.Utilities/NaughtyAttributes/Editor/Utility/PropertyUtility.cs:20)
NaughtyAttributes.Editor.PropertyUtility.GetAttribute[T] (UnityEditor.SerializedProperty property) (at Assets/Decay.Utilities/NaughtyAttributes/Editor/Utility/PropertyUtility.cs:14)
NaughtyAttributes.Editor.NaughtyInspector+<>c.<OnInspectorGUI>b__6_0 (UnityEditor.SerializedProperty p) (at Assets/Decay.Utilities/NaughtyAttributes/Editor/NaughtyInspector.cs:39)
System.Linq.Enumerable.Any[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
NaughtyAttributes.Editor.NaughtyInspector.OnInspectorGUI () (at Assets/Decay.Utilities/NaughtyAttributes/Editor/NaughtyInspector.cs:39)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass55_0.<CreateIMGUIInspectorFromEditor>b__0 () (at <90d4bcb003fb405fb09241aed2f178aa>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
`

How to reproduce:
1. Create a script
2. Attach it to a gameobject
3. Remove the script from project files
4. View gameobject and inspect console

**Comment by fmoo** [comment]
I ran into a similar issue when I accidentally added a second ScriptableObject subclass to a file that already had one.

**Comment by slimshader** [comment]
Confirmed also

**Comment by dbrizov** [comment]
Fixed in 842f290e6d4e8fcc4a870458650b08af84f2dcf6
