### ISSUE TITLE
Slow down in inspector with 'ShowIf'

### ISSUE THREAD

**Issue by ColorTwist** [dbrizov/NaughtyAttributes#163]
I really love Naughty Attributes!
Lately, I started a new project, I noticed that when adding **one**  'ShowIf' "[ShowIf("IsAnimated")]"
The whole script is getting slower, like typing, characters/numbers in any string field takes longer, like more time to process (slight delay but noticeable and annoying) compare to when removing the 'ShowIf' it works much smoother.
Is that expected behavior with 'ShowIf'?
Note that the script is kinda big with many parameters.
I am using Unity 2019.3.11

**Comment by snorrsi** [comment]
@ColorTwist check out issue #133 .. seems to be the same problem. Easy quick fix workaround would be to remove the ShowIf usage , use Header instead or labels. Check out my answer in the other thread which explains roughly how I fixed it for myself

**Comment by ColorTwist** [comment]
oh, i see, yeah the same issue. 
Currently, I am removing Naughty Attributes as for me, the inspector becomes too slow and annoying.
I use the  'ShowIf' pretty much, one of my favorites.

**Comment by dbrizov** [comment]
Same as #133
I know about this issue. The problem is that I am not doing any caching at all. I need to go through the attributes one by one, check what is slow and fix it. I will try to fix it in the next release.

**Comment by NeatWolf** [comment]
Thanks for the asset @dbrizov !

I'm on v2, ShowIf+Box, and experiencing the same issue on a gaming rig!
Using Unity 2019.4.2f1 (LTS)
I would gladly pay in the Asset Store to support you in the development.

At this point some caching is really mandatory I guess (I believe ODIN is already doing that).
