### ISSUE TITLE
ShowIf, HideIf, EnableIf, DisableIf NOT working on string variables

### ISSUE THREAD

**Issue by ReGaSLZR** [dbrizov/NaughtyAttributes#166]
Title is self-explanatory. :) I followed the sample code syntax but the said tags do not work specifically on string variables. It does work on all the other data types tho. Any idea why? 

If it helps, I'm using package version 2.0.3. If this is fixed on the newest releases, please let me know. Otherwise, I'm scared to update fearing it might break some parts of my existing codebase. 🙇‍♀️

**Comment by dbrizov** [comment]
It is working on string variables both in 2.0.3 and 2.0.4.
What Unity version are you using? Are there any other plugins like property drawers for strings and so on that can interfere with NaughtyAttributes?

**Comment by ReGaSLZR** [comment]
Oh, wow! Thank you so much for the quick response.
I'm afraid I'm not using any other plugin that has custom Editors and property drawers.
Here's my Unity version: 2019.3.1f1.

And here are some screenshots:
<img width="315" alt="Screen Shot 2020-06-30 at 16 41 03" src="https://user-images.githubusercontent.com/50439252/86098207-c21fc200-baf0-11ea-8abe-af7db8c7c783.png">
<img width="301" alt="Screen Shot 2020-06-30 at 16 41 34" src="https://user-images.githubusercontent.com/50439252/86098243-ce0b8400-baf0-11ea-83b1-35d3bdbb6297.png">

**Comment by dbrizov** [comment]
The names of the variables don't match the ones in the inspector. In the code it's `textOptionRight`, so in the inspector it should be `Text Option Right`, but it is `Option Text Right` instead. Do you by any chance have a custom editor for this script?

**Comment by ReGaSLZR** [comment]
Oh! My bad, I posted an outdated screenshot from a previous compile. Here's the new one with the correct/matching variable names and still, the string var is still not disabled.

<img width="305" alt="Screen Shot 2020-06-30 at 16 52 49" src="https://user-images.githubusercontent.com/50439252/86099321-4de61e00-baf2-11ea-9680-c5073d0841e7.png">

**Comment by dbrizov** [comment]
Ok, thanks. I will try to reproduce it when I get home.

**Comment by ReGaSLZR** [comment]
Thank you very much and I'm sorry for the bother 🙇

**Comment by dbrizov** [comment]
Mate, just tested it, and it's working on my end.
I tested it with Unity **2019.3.11f1** and **2019.4.f1**. Both the **2.0.3** and **2.0.4** versions of NaughtyAttributes.
Try to update your Unity, but I don't think that will help. There is no reason for it not to work with the version you have. The only reason would be some custom editor. If you haven't written any, then please check for some plugins that might do some global string overrides. The easiest way to do so is to just try to reproduce it in a new empty project - if it works, then 100% some plugins are interfering with NaughtyAttributes. Also, are you using a Mac, or a Windows PC?
![image](https://user-images.githubusercontent.com/3619573/86207869-20dc4e80-bb78-11ea-82be-42092a4091ef.png)
![image](https://user-images.githubusercontent.com/3619573/86207972-4ff2c000-bb78-11ea-9218-30d012227eb6.png)
![image](https://user-images.githubusercontent.com/3619573/86208128-a19b4a80-bb78-11ea-8423-88f1236c79e1.png)

**Comment by ReGaSLZR** [comment]
I'm using a Mac.

I see. Then, I probably have another plugin which I am not aware has custom editors/property drawers. Thank your for the verification and sorry again for the bother. I'll close this ticket and just update it when I have new findings.

Have a great day!

**Comment by dbrizov** [comment]
It might be a Mac issue then. Unfortunately, I don't have a Mac, and can't do anything :(

**Comment by ReGaSLZR** [comment]
It's alright. You've already done plenty. Thanks for everything.
I'll still try to debug this issue.

**Comment by ReGaSLZR** [comment]
Hello, I'm just chiming in again, this time with the name of the culprit. 🤣 TextMeshPro. I can officially say this issue is so closed now. Thank you for the quick responses and the investigation done on your end, @dbrizov . Have an awesome week. 👋

**Comment by dbrizov** [comment]
It's good and bad news I guess :(
I need to start thinking about integration with 3rd party plugins.
Anyway mate, I am glad we found the culprit. Wish you an awesome week as well :)

**Comment by ReGaSLZR** [comment]
Hello, dev. 👋 
Just chiming in again with an input that may help you with your future releases.

When I refactored some stuff and turned my MonoBehaviour script into a ScriptableObject, the tags on the string variables now work. Take a look at these screenshots:

<img width="298" alt="Screen Shot 2020-07-07 at 16 09 47" src="https://user-images.githubusercontent.com/50439252/86734136-b4c48380-c06c-11ea-87e5-ff1eaf8395ae.png">
<img width="296" alt="Screen Shot 2020-07-07 at 16 10 34" src="https://user-images.githubusercontent.com/50439252/86734155-b8580a80-c06c-11ea-85ae-a22fa050e554.png">
<img width="295" alt="Screen Shot 2020-07-07 at 16 10 01" src="https://user-images.githubusercontent.com/50439252/86734174-bbeb9180-c06c-11ea-92d5-7e234a017be8.png">

P.S. I still have TextMeshPro in my project.
