### ISSUE TITLE
[Request] Enum support for ShowIf/HideIf + EnableIf/DisableIf 

### ISSUE THREAD

**Issue by TrapShooter** [dbrizov/NaughtyAttributes#167]
So basically you could say:

public enum Test { OptionA, OptionB, OptionC }
public Test testEnum;

[ShowIfEnum ("testEnum", 1)]
public float health;

I know of another extension class that has this functionality. The link is below, if you read the comments you'll find the enum improvements.

http://www.brechtos.com/hiding-or-disabling-inspector-properties-using-propertydrawers-within-unity-5/

**Comment by Eyap53** [comment]
Duplicate of #141 .
It would remove the need to create custom method for each enum just for this, so i believe it may still be useful.

**Comment by dbrizov** [comment]
There is a PR for that - #223

**Comment by konsnos** [comment]
Do ShowIf/HideIf support multiple Enums or should I create a new request for that? (I'm new to NaughtAttributes. Amazing tool!)

**Comment by dbrizov** [comment]
What do you mean by multiple enums? Right now it supports enum values and enum flags (see #217)

**Comment by konsnos** [comment]
More like this.
```
public class NaughtyComponent : MonoBehaviour
{
    public EMyEnum enumFlag;

    [ShowIf("enumFlag", EMyEnum.Case0, EMyEnum.Case1)]
    public int enableIfEnum; // Will be shown only if enumFlag == EMyEnum.Case0 or EMyEnum.Case1
}

public enum EMyEnum
{
    Case0,
    Case1,
    Case2
}
```
I've read the documentation of Enum Flags and I think they are something entirely different, isn't it?

**Comment by adamroszyk** [comment]
Any progress on this?
Would be amazing to have this feature.
