### ISSUE TITLE
OnValueChanged current only work with MonoBehaviours, i want it work with regular class/struct

### ISSUE THREAD

**Issue by HyVong007** [dbrizov/NaughtyAttributes#169]
As the title said, i have no more to say.

**Comment by dbrizov** [comment]
It's already working for classes and structs.
[OnValueChanged](https://dbrizov.github.io/na-docs/attributes/meta_attributes/on_value_changed.html)
[AllowNesting](https://dbrizov.github.io/na-docs/attributes/special_attributes/allow_nesting.html)

**Comment by HyVong007** [comment]
> It's already working for classes and structs.
> [OnValueChanged](https://dbrizov.github.io/na-docs/attributes/meta_attributes/on_value_changed.html)
> [AllowNesting](https://dbrizov.github.io/na-docs/attributes/special_attributes/allow_nesting.html)

Oh i am so sorry for the mistake ! I have not read all carefully !. sorry

**Comment by HyVong007** [comment]
> It's already working for classes and structs.
> [OnValueChanged](https://dbrizov.github.io/na-docs/attributes/meta_attributes/on_value_changed.html)
> [AllowNesting](https://dbrizov.github.io/na-docs/attributes/special_attributes/allow_nesting.html)

Hey [OnValueChanged] doesNOT get the current value after i edit in Inspector ? It happens when "Before Serialize" ?
Here the code and result:

``
using NaughtyAttributes;
using System;
using UnityEngine;


public class Test : MonoBehaviour
{
	public S s;
}


[Serializable]
public struct S
{
	[OnValueChanged("Callback")]
	[AllowNesting]
	public int i;


	private void Callback()
	{
		Debug.Log(i);
	}
}
``

I press Play and enter 1, then it prints "0", i want it prints "1" !

![image](https://user-images.githubusercontent.com/20169967/88068000-d3ad3480-cb99-11ea-8b43-dba1cfbc8191.png)

**Comment by dbrizov** [comment]
That's pretty strange mate. I am testing it on my end, and I get the new value. What Unity version are you using? Are you using a Mac?

**Comment by dbrizov** [comment]
Ok, I actually reproduced it. The problem is related with the fact that **S** is a struct and not a class. There is a similar issue with the [Dropdown] attribute in nested structs - the value of the dropdown just doesn't update. Unfortunately, I don't know how to fix it. It has to do with boxing/unboxing objects value type objects.
