### ISSUE TITLE
[Issue] ShowNativePropertyAttribute doesn't support ulong type

### ISSUE THREAD

**Issue by StromKuo** [dbrizov/NaughtyAttributes#173]
![image](https://user-images.githubusercontent.com/14904676/91409416-f527cd00-e877-11ea-9a52-51f11250e8cf.png)

**Comment by dbrizov** [comment]
I am depending on Unity's API here. Unfortunately, `EditorGUILayout` doesn't have any functions for `ushort`, `uint` or `ulong` type fields. The only solution, for now, is to use `long` instead :(

**Comment by dbrizov** [comment]
There is a pull request #183
