### ISSUE TITLE
[Issue] Expandable does not work on classes inherited from ScriptableObject

### ISSUE THREAD

**Issue by TforTrevor** [dbrizov/NaughtyAttributes#174]
![Annotation 2020-08-28 030342](https://user-images.githubusercontent.com/36804391/91531663-22f22d80-e8db-11ea-8686-35f0a60e862e.png)

**Comment by dbrizov** [comment]
Oh, I know what is happening here. I am checking for ScriptableObject in specific, I also need to check for derived classes, thanks. I will fix it.

**Comment by krisrok** [comment]
Nice coincidence, I created a pull request for this just now without seeing the issue.
#175

**Comment by dbrizov** [comment]
Merged into **v2** - b3a9066bda6b6f81e34d6cd88efd34f2a63f50a6
