### ISSUE TITLE
[Request] Documentation about NaughtyInspector usage

### ISSUE THREAD

**Issue by krisrok** [dbrizov/NaughtyAttributes#176]
I only saw the info in the readme.md stating some attributes need the NaughtyInspector to work correctly. Maybe I overlooked something?

1. How do we know what attributes are affected?
2. Is it sufficient to create a simple "empty" Inspector class (see below) for the classes using the affected attributes? Provide an example.

```
public class MyInspector : NaughtInspector
{ }
```

**Comment by dbrizov** [comment]
Thanks. I will update the documentation. Basically only the custom attributes won't work. By custom, I mean the ones that aren't using Unity's property drawer system - `ReorderableList`, `Button`, `ShowNonSerializedField`, `ShowNativeProperty`. All **meta** attributes won't work as well - `EnableIf`, `DisableIf` and so on...

**Comment by dbrizov** [comment]
Documented in abea5e9e7cde63551215259850991d5d43c7b48b
