### ISSUE TITLE
[Request] Allow folding ReorderableList

### ISSUE THREAD

**Issue by MostHated** [dbrizov/NaughtyAttributes#178]
Hey there,
    I just wanted to request the functionality of being able to fold a ReorderableList. Having a foldable paged list would be amazing, but I won't push my luck, lol.

I definitely appreciate all the work you put into this package!
Thanks,
-MH

**Comment by dbrizov** [comment]
Hi. There is no such functionality in the API for ReorderableList that Unity provides. What you can do is to use a Foldout group like so:

```
[Foldout]
[ReorderableList]
public List<int> someList;
```

Is this good enough?

**Comment by MostHated** [comment]
I want to say I tried that last night and it simply didn't do anything. I will try it again and make sure I did it just as you did there. I might have not had that same order of attributes.

**Comment by MostHated** [comment]
Yeah, here is what I have there. 
```cs
[Foldout("Referenced ScriptableObjects")]
[ReorderableList] 
public List<ReferenceScriptableObject> referenceScriptableObjects = new List<ReferenceScriptableObject>();
```
Here is what I end up with.
![](https://i.imgur.com/MYFvpgX.png)

**Comment by MostHated** [comment]
Ok, yeah, my apologies. It looks like it is working fine. I forgot I renamed something and was looking at the wrong list. >_< My bad.

**Comment by dbrizov** [comment]
Don't worry, I am glad it's working. The order of attributes is of no difference. The order matters only with decorator drawers.
