### ISSUE TITLE
ShowIf, HideIf, EnableIf, DisableIf does not work inside structs nested in a class.

### ISSUE THREAD

**Issue by venediklee** [dbrizov/NaughtyAttributes#179]
As shown in the image[1], a variable inside a struct nested inside a class can't use show/hide/enable/disable attributes.  

This is different from #142 as the variable is not a list or an array.  

Also as shown in the second image[2] if the variable has MinMaxSlider(or ShowAssetPreview) attributes, the above mentioned attributes work.  

[1 - SpawnChanceMultiplier is not hidden, LimitedSpawnBounds is hidden] ![image](https://user-images.githubusercontent.com/36706533/91661951-024af300-eae8-11ea-8cf7-d517f129d845.png)  

[2- LimitedSpawnBounds becomes visible when SpawnLimitedAmount is set to true]  
![image](https://user-images.githubusercontent.com/36706533/91662016-6d94c500-eae8-11ea-9bf0-8553c3728bba.png)

**Comment by dbrizov** [comment]
You have to add the [AllowNesting](https://dbrizov.github.io/na-docs/attributes/special_attributes/allow_nesting.html) attribute, and it will work ;)
