### ISSUE TITLE
[Request] ReorderableList. Add/Remove element from any position

### ISSUE THREAD

**Issue by dasannikov** [dbrizov/NaughtyAttributes#182]
I saw nice feature in [Demilib](https://github.com/Demigiant/demilib) 
Add/Remove element from any position for lists/arrays.

![Annotation 2020-09-03 111305](https://user-images.githubusercontent.com/1015770/92096138-d45efa80-edd6-11ea-95c7-e8d96fda8a35.png)

**Comment by dbrizov** [comment]
You can right-click on an element and duplicate an element
