### ISSUE TITLE
'EditorGUILayout' does not contain a definition for 'BeginFoldoutHeaderGroup'

### ISSUE THREAD

**Issue by revolt3r** [dbrizov/NaughtyAttributes#184]
Unity 2018.4

'EditorGUILayout' does not contain a definition for 'BeginFoldoutHeaderGroup'
error CS0117: Library\PackageCache\com.dbrizov.naughtyattributes@ed0edab05e0503622f0b6c6b41061d5fb64e3ece\Scripts\Editor\Utility\NaughtyEditorGUI.cs(118,27)

![image](https://user-images.githubusercontent.com/11783754/94400787-f34c7480-0169-11eb-948e-e5fd30080925.png)

**Comment by Waffle1434** [comment]
Same here, Unity 2018.4.25f1

**Comment by dbrizov** [comment]
Oh, my bad. I merged a pull request for a foldout attribute. I didn't know the function used are not present in 2018.4. Just comment the code until I fix it. I will do it as soon as possible.

**Comment by dbrizov** [comment]
Fixed in 777dd313f4dc77cf8c5161f9352be680c2838d98
