### ISSUE TITLE
[Issue] Bug concerning the Expandable attribute

### ISSUE THREAD

**Issue by rouxfrancis** [dbrizov/NaughtyAttributes#185]
When I select multiple gameobjects of the same type, the references to the scriptableObjects they contain are corrupted. This happens in case I use the Expandable attribute.

Example on this link: https://fromsmash.com/Expandable-Issue

**Comment by dbrizov** [comment]
Fixed in 3944fec482fe883c70394bc8b2c680bb720578bd
