### ISSUE TITLE
[Small Request] Rich text for ReorderableListPropertyDrawer

### ISSUE THREAD

**Issue by Samhayne** [dbrizov/NaughtyAttributes#189]
Hey @dbrizov :)
Sometimes it's the small things.

Would you mind enabling rich text for the ReorderableList LabelField?

Changing the label code like this in ReorderableListPropertyDrawer.cs...

```
GUIStyle style = EditorStyles.boldLabel;
style.richText = true;
EditorGUI.LabelField(r, string.Format("{0}: {1}", label.text, property.arraySize), style /*EditorStyles.boldLabel*/);
HandleDragAndDrop(r, reorderableList);
```
allowed me to do this:

![image](https://user-images.githubusercontent.com/7030482/97880888-febf2c80-1d21-11eb-80f1-af4c13bfb283.png)

..when combined with a
``
[Label("GameObjects to <color=green>INCLUDE</color>")]
``
attribute.

**Comment by dbrizov** [comment]
That's a great idea. I will :)

**Comment by Samhayne** [comment]
Rich text support for button texts would also be nice. :)

Added it for me in NaughtyEditorGUI.cs:

``
if (GUILayout.Button(buttonText, new GUIStyle(GUI.skin.button) {richText = true}))
``

**Comment by dbrizov** [comment]
Added into the **v2** branch: aa20fa37b97f3b871c3f90621cc2c79fd181b483
