### ISSUE TITLE
Attributes are not working in structs

### ISSUE THREAD

**Issue by Skittluier** [dbrizov/NaughtyAttributes#19]
Hi,

The attributes I am trying to use are not working in a struct I made Serializable. _(System.Serializable)_
These are the attributes I'm trying to use: "ReadOnly" and "OnValueChanged".

**Comment by dbrizov** [comment]
It's not only structs. The nesting is the problem.
Unfortunately, I will need to rewrite a lot of code to make it work. The architecture of the whole thing is not as flexible as I wanted it to be. The other thing I can do is to somehow make a workaround, but I really don't want to make hacky things like that. I will try to think of something.

**Comment by cmlewis89** [comment]
This would be amazing, interested to hear a description if the hack / work-around. Just incase it's easy to implement on a fork in the mean time.

**Comment by FomTarro** [comment]
having this work for nesting would be a huge value add for the project, i think

**Comment by Zehir** [comment]
Can you please add an warning section to the read me for this?

**Comment by stopiccot** [comment]
Any update on this. Really need to get LabelAttribute working in nested objects

**Comment by dbrizov** [comment]
Same as #91
