### ISSUE TITLE
[Issue] https://github.com/dbrizov/NaughtyAttributes.git#upm doesn't work

### ISSUE THREAD

**Issue by mwdowski** [dbrizov/NaughtyAttributes#191]
Hi,
when I try to open a project with "https://github.com/dbrizov/NaughtyAttributes.git#upm" in manifest, I get this error:

"An error occurred while resolving packages:
  Project has invalid dependencies:
    com.dbrizov.naughtyattributes: Cannot checkout repository [https://github.com/dbrizov/NaughtyAttributes.git]:
      Error when executing git command. fatal: reference is not a tree: 8361c4c50a4f375cfac3cdb67ebd3babf15c42d8"

How can I fix this? Other dependencies from git and with #upm work fine.

**Comment by dbrizov** [comment]
You have to manually remove the lock of naughty attributes from the **Packages/packages-lock.json**.
![image](https://user-images.githubusercontent.com/3619573/98444813-88a13800-211c-11eb-9d31-b7a0e598f989.png)

Sorry about that, it is connected with a bug that I fixed a couple of days ago: #188
