### ISSUE TITLE
[Request] Draw checkbox before label instead of after

### ISSUE THREAD

**Issue by MSavioti** [dbrizov/NaughtyAttributes#192]
Is usually annoying how the checkbox is drawn and how often it hides the field label:

![image](https://user-images.githubusercontent.com/34958918/98879866-469e2c00-2465-11eb-8774-fdb6e4249551.png)

There's an expensive serializer that can draw the checkbox before the label with the attribute `[ToggleLeft]` (image taken from their site):

![image](https://user-images.githubusercontent.com/34958918/98880525-b365f600-2466-11eb-9570-cc3618a88cab.png)

Is possible to add this to Naughty Attributes?

Thanks in advance, your open source project helps a lot of people like me who live in countries where an unity asset can cost half of the average people monthly income.

**Comment by dbrizov** [comment]
Unity's editor UI is working that way - the checkbox is on the right. I can probably make something about it, but I don't think it's worth it. The way to do it is to create a custom property drawer for boolean fields
