### ISSUE TITLE
Reorderable List Attribute breaks rendering with Property-Drawered properties

### ISSUE THREAD

**Issue by peeweek** [dbrizov/NaughtyAttributes#193]
While getting rid some old (Apr 21 2019) version of NaughtyAttributes I used in my Gameplay Ingredients package, I stumbled upon a break in the behavior of Reorderable List Attributes.

Reproduced with 2020.1.13f1 / current 2.0.7 (cloned your project to have a boilerplate project that's vanilla)

Seems that Reorderable List property drawer sends incorrect Rect to custom property drawers

In this image : Range Float is broken in the Reorderable List (no Field) but SomeClass uses default PropertyField correctly
![image](https://user-images.githubusercontent.com/4037271/98968141-96d0c900-250d-11eb-8f98-4b062112db49.png)

In this Image I created a Custom Property Drawer for `SomeClass` fields:
![image](https://user-images.githubusercontent.com/4037271/98968664-40b05580-250e-11eb-8851-f610d991ba4a.png)

This PropertyField Custom property drawer is just a pass-through for a propertyfield : 
```using UnityEngine;
using UnityEditor;

[CustomPropertyDrawer(typeof(SomeClass))]
public class SomeClassPropertyDrawer : PropertyDrawer
{
    public override void OnGUI(Rect position, SerializedProperty property, GUIContent label)
    {
        EditorGUI.PropertyField(position, property);
    }
}
```

While debugging, seems that the Rect being sent has incorrect size (position seems correct but could be confirmed): 
![image](https://user-images.githubusercontent.com/4037271/98968806-72c1b780-250e-11eb-89a0-d9617f4b983a.png)

I enclosed a repro-case unitypackage, not sure if it's related to your drawer. Seems that old ReorderableList code did not repro this problem ( at least the one I use in my gameplay-ingredients package which is antique :) )

[NaughtyAttributes-ReorderableListReproCase.zip](https://github.com/dbrizov/NaughtyAttributes/files/5531977/NaughtyAttributes-ReorderableListReproCase.zip)

**Comment by peeweek** [comment]
Figured out the issue! :) (At least to be confirmed)

Seems that `ReorderableListPropertyDrawer:60` was:
`EditorGUI.PropertyField(new Rect(r.x, r.y, r.width, 0), element, true);`
now works with:
`EditorGUI.PropertyField(new Rect(r.x, r.y, r.width, EditorGUIUtility.singleLineHeight), element, true);`

![image](https://user-images.githubusercontent.com/4037271/98970727-8e2dc200-2510-11eb-9cad-993f0f0bc211.png)

**Comment by dbrizov** [comment]
Hey, thanks. I will merge the pull request :)

**Comment by peeweek** [comment]
Thank you ❤️

**Comment by peeweek** [comment]
Hello! Could you merge this PR please? (Also, if you have time, could you push an updated version to OpenUPM with this fix?)

**Comment by dbrizov** [comment]
@peeweek Hey. Sorry for the delay dude, I will try to merge it in the upcoming weekend. I'm pretty busy these couple of months. I also have some other issues that I want to address and make a new release.

**Comment by dbrizov** [comment]
I merged the pull request into the **v2** branch: f188911da9bd764d6538d3efdfea4f35bc518265
