### ISSUE TITLE
[Request] Make Foldouts label clickable to expand foldout

### ISSUE THREAD

**Issue by PhiSel** [dbrizov/NaughtyAttributes#197]
The label for foldouts is in the current version not clickable; therefore, user have to click precisely on the little triangle on the left side of the label. To improve the usability, please add the following bool:

`_foldouts[group.Key].Value = EditorGUILayout.Foldout(_foldouts[group.Key].Value, group.Key, true);`

https://github.com/dbrizov/NaughtyAttributes/blob/b608ef49294bbdcc960ddd3a6d8c944e12e70781/Assets/NaughtyAttributes/Scripts/Editor/NaughtyInspector.cs#L123

**Comment by dbrizov** [comment]
Implemented in **v2** branch: 473fb3b461eeac3e62a6a1d7906465756c8929d5
