### ISSUE TITLE
List of Scene

### ISSUE THREAD

**Issue by slimshader** [dbrizov/NaughtyAttributes#199]
Hi,

is it possible to propagate attributes to ReordableList? Say I want a [ReordableList] but only of [Scene], I tried

```
[ReordableList]
[Scene]
public List<string> scenes;
```

but it only shows scene dropbox with single element (scene with id 0)

**Comment by dbrizov** [comment]
Usually, you can combine them. I've tested it with sliders and other attributes, and it's working. If this doesn't work it's a bug. I will fix it

**Comment by slimshader** [comment]
> Usually, you can combine them. I've tested it with sliders and other attributes, and it's working. If this doesn't work it's a bug. I will fix it

Thanks. Additoinal: when using [ReordableList] with [Dropdown] it also does not work for me. I am working around the issue with struct wrapper around string for now like so:

```
[Serializable]
struct Property
{
   [Dropdown("GetValues")]
   public string Value;
}

[ReordableList]
List<Property> _properties;
```

**Comment by dbrizov** [comment]
As of Unity **2020.2.x** all lists are reorderable by default, so you no longer have to use the custom [ReorderableList] attribute. You just have to put the [Scene] attribute on top of the list field.
