### ISSUE TITLE
Updated to 2017.3.1f1 and NA stopped working

### ISSUE THREAD

**Issue by thebspin** [dbrizov/NaughtyAttributes#20]
Even tried getting the latest version from GIT but no succes. Buttons are not being drawn in the inspector and my script attached to OnValueChanged is not firing. Not sure what else i can add to find the issue...

**Comment by dbrizov** [comment]
I updated to 2017.3.1f1, and it's working on my end. Even updated to 2018.1.0.f2 to see if the newer version will have any issues, and it's still working. Have you made any modifications to the plugin? Also, can you tell me the signature of the method? It should display a warning if the signature of the method isn't correct though. OnValueChanged should also display warnings if something isn't set up right.
