### ISSUE TITLE
When using [AllowNesting] on nested serialized objects, the default lists unfolding is not drawing a proper rect

### ISSUE THREAD

**Issue by JovianIndustries** [dbrizov/NaughtyAttributes#200]
Let's say I have this structure

SerializedClass1
{
     bool show;
     [ShowIf("show")]
     [AllowNesting]
     public SerializedClass2 serializedClass2
}

SerializedClass2
{
     public string string1;
     public string string2;
     public string string3;
}

When serialized class 2 unfolds in the inspector, the rect is not drawn properly and fields overlap with the ones bellow.

Tested on Unity 2020.2.1f1

**Comment by dbrizov** [comment]
This indeed is a bug. I don't get why my other test cases with nesting work. This is not that different, it's even simpler. I am looking at it now

**Comment by dbrizov** [comment]
Fixed in the **v2** branch - 0183cca6c6dcac9dcf193e3634b5cb3025f371a1
