### ISSUE TITLE
EnableIf/DisableIf in [Serializable] classes

### ISSUE THREAD

**Issue by slimshader** [dbrizov/NaughtyAttributes#201]
Hi, it seems EnableIf/DisableIf don't work when used in custom [Serializable] class:

```
[Serializable]
class MyClass
{
  [ShowIf("ShouldShow")]
  string _value;

  private bool ShouldShow => true;
}
```

same code works when used directly in Monobehaviour

**Comment by dbrizov** [comment]
You need to use the [AllowNesting](https://dbrizov.github.io/na-docs/attributes/special_attributes/allow_nesting.html). Check the link I gave you :)

**Comment by unnanego** [comment]
Doesn't seem to work anymore( I'm using Unity 2021.3.22
