### ISSUE TITLE
[Issue] Foldout can't be used with collections

### ISSUE THREAD

**Issue by RunninglVlan** [dbrizov/NaughtyAttributes#205]
```csharp
namespace NaughtyAttributes.Test
{
  public class FoldoutTest : MonoBehaviour
  {
    [Foldout("Integers")]
    public int int0;
    [Foldout("Integers")]
    public int int1;

+   [Foldout("List of Integers")]
+   public int[] int2;
+   [Foldout("List of Integers")]
+   public int[] int3;
    ...
  }
}
```

![image](https://user-images.githubusercontent.com/11376741/105182812-27dba600-5b36-11eb-9663-ae1e96023ded.png)

**Comment by bhupiister** [comment]
Can you try making making your collection as scriptable object and then try ?
Look for my comment in the link below.
[https://forum.unity.com/threads/draw-a-field-only-if-a-condition-is-met.448855/#post-7185823](url)

**Comment by RunninglVlan** [comment]
Looks like this might be related to Unity version, because I can't reproduce it with the same version of NaughtyAttributes I used when creating this issue (probably 2.0.8, I checked out 0c4ba806 from 12-Jan) and one of the latest Unity versions - 2021.1.7f1
![image](https://user-images.githubusercontent.com/11376741/120066834-027d1c80-c081-11eb-927a-24da046784bd.png)
So I guess this can be closed
