### ISSUE TITLE
[Request] ContextMenu attribute

### ISSUE THREAD

**Issue by AndrewRZcoder** [dbrizov/NaughtyAttributes#208]
Can you "hack" UnityEngine.ContextMenu attribute?
I try/want use [ContextMenu] instead of [ContextMenu("nameString")]. I'm trying to create something like this, but my skill is not hi, and i can't do this now(.

**Comment by dbrizov** [comment]
Just use Unity's ContextMenu, why do you need another attribute which does the same?
