### ISSUE TITLE
[Issue] Multi-selection of objects with a dropdown overwrites all values to be the value of the last object selected

### ISSUE THREAD

**Issue by cookie966507** [dbrizov/NaughtyAttributes#209]
Example: [NaughtyAttributes.Scene]

Setup: Populate a few scenes and add them to the build settings. Create several gameobjects in a scene and create a script that looks like this:

```
using UnityEngine;

public class Test : MonoBehaviour
{
    [NaughtyAttributes.Scene]
    public int scene;
}
```

Attach the "Test" script to each of the gameObjects in the scene. Assign each one a different value. Shift select all of the gameObjects (notice that they do not display the standard "---" Unity displays with something like Enums).

Check each object individually and notice that they all have had their original values overridden even though the dropdown wasn't used.

**Comment by dbrizov** [comment]
Fixed in dcae7a651a284e1f9c8104ce8070112bad71da01
