### ISSUE TITLE
[Issue] Dropdown doesn't save first value by default

### ISSUE THREAD

**Issue by kirpit** [dbrizov/NaughtyAttributes#213]
```
using UnityEngine;
using NaughtyAttributes;

[CreateAssetMenu(fileName="New Naugty Item", menuName="Naugty Item", order=61)]
public class NaughtyScriptable : ScriptableObject
{
    [Dropdown("_intValues")]
    public int intDropdown;
    private int[] _intValues = new int[] {10, 20};
    
    [Dropdown("_stringValues")]
    public string stringDropdown;
    private string[] _stringValues = new string[] {"SILVER", "GOLD"};
}
```

### Steps to repeat:

- Drop the above code in your project. 
- Create a new scriptable asset by "Assets => Create => Naugty Item" (perhaps in your Resources folder). 
- Do **not** change any value and leave as is. 
- Load the created asset and display its values; intDropdown / stringDropdown

### Expected result
`intDropdown == 10` and `stringDropdown == "SILVER"` as it displays on the inspection menu when first created.

### Actual result
`intDropdown == 0` and `stringDropdown == ""` which are the default values of an `int` and `string`.

To have them set the first given values, you need to click to the dropdown in inspection and explicitly choose the first value that is visually no different then leaving it as it was. This is overall misleading and took me quite a few hours to understand where the problem is.

Thanks for the great library though, much appreciated.

**Comment by dbrizov** [comment]
Fixed in 325696fe42c0f7f0069c543a1c377c8ba35822ae
