### ISSUE TITLE
il2cpp error unity 2020

### ISSUE THREAD

**Issue by aminbarzegari** [dbrizov/NaughtyAttributes#214]
![image](https://user-images.githubusercontent.com/48697012/110216985-e117f480-7ec6-11eb-9b28-ae4f76112621.png)

![image](https://user-images.githubusercontent.com/48697012/110217011-0d337580-7ec7-11eb-9d59-79421c3fa7c4.png)

**Comment by aminbarzegari** [comment]
error while build to il2cpp for android, on unity 2020.2

**Comment by IF-ACT** [comment]
You refered the Editor assambly in your script? These are editor-only code, do not include this assambly in your project.
![image](https://user-images.githubusercontent.com/44696723/114263150-7ce0d700-9a16-11eb-888a-ab78317142c9.png)

**Comment by aminbarzegari** [comment]
> You refered the Editor assambly in your script? These are editor-only code, do not include this assambly in your project.
> ![image](https://user-images.githubusercontent.com/44696723/114263150-7ce0d700-9a16-11eb-888a-ab78317142c9.png)

NaughtyAttributes does not have  dll or aar plugin file to disable android platform!

**Comment by IF-ACT** [comment]
I mean, the code where this error occurs shouldn't appear in your build, no matter which platform you are using.
In the folder NaughtyAttributes/Scripts/Editor, you should find a file named `NaughtyAttrubutes.Editor.asmdef`, click it, and make sure in the setting `Platforms`, only option `Editor` checked.
Then check your scripts, the namespace `NaughtyAttributes.Editor` should never be used.

**Comment by dbrizov** [comment]
What @IF-ACT  said
