### ISSUE TITLE
[Request] Support Enum Flags

### ISSUE THREAD

**Issue by marcusx2** [dbrizov/NaughtyAttributes#217]
For the ShowIf/HideIf attribute, please allow Enum Flags as input. For example:

```
[Flags] public enum Pets {
   None = 0,
   Dog = 1,
   Cat = 2,
   Bird = 4,
   Rabbit = 8,
   Other = 16
}

private Pets pets = Pets.Dog |  Pets.Cat;
[ShowIfEnum("pets", Pets.Dog)]
public int myint;//will show if pets has Dog flag

```

Please see [https://forum.unity.com/threads/draw-a-field-only-if-a-condition-is-met.448855/](https://forum.unity.com/threads/draw-a-field-only-if-a-condition-is-met.448855/) for reference

Here's the code snippet that does the trick with this other library:
```
// get the value & compare based on types
switch (comparedField.type)
{ // Possible extend cases to support your own type
case "bool":
	return comparedField.boolValue.Equals(drawIf.comparedValue);
case "Enum":
	return (comparedField.intValue & (int)drawIf.comparedValue) == (int)drawIf.comparedValue;
default:
	Debug.LogError("Error: " + comparedField.type + " is not supported of " + path);
	return true;
}
```

Please note that the code above for enum works if it's a normal enum as well. So if it's a flag enum or normal enum it will work.

**Comment by marcusx2** [comment]
I know it can be done with functions, but there are so many fields in the enum that it's just not practical. Please support enum flags like you support bool

**Comment by dbrizov** [comment]
Duplicates #167

**Comment by marcusx2** [comment]
@dbrizov Does the new update support enum flags, or just normal enum?

**Comment by marcusx2** [comment]
Thanks haha. It would be great if enum flags were supported as well. Please see the code snippet I posted, the case enum. It handles enum flags as well so I can select multiple items on a dropdown.

**Comment by dbrizov** [comment]
Done in 7a2d8e17a2a979a484a32aa9d3bc17daed0a4e12
