### ISSUE TITLE
[Request] DefaultValueIfShowing

### ISSUE THREAD

**Issue by marcusx2** [dbrizov/NaughtyAttributes#218]
Have an attribute to change the default value of a property based on the fact that said property is showing/hiding/enabled/disabled in the inspector. For example, I can have a property that the default value is 2. But if it's hidden from the inspector, I don't want its value to be 2, I want it to be null, for example. 

Having a default value comes from the assumption that you are using said value. If it's hidden or disabled in the inspector, you may want to invalidate it, because the user is not supposed to use it.

I know this can be done using the OnValueChanged attribute. While OnValueChanged is very powerful and incredibly useful, I think it's overkill for this use case.

**Comment by dbrizov** [comment]
I think this is confusing. When it is hidden it changes its value to null. This can be misunderstood as a bug even.
