### ISSUE TITLE
Creating custom ReorderableList Property Drawers (eg: with dropdown menu)

### ISSUE THREAD

**Issue by peeweek** [dbrizov/NaughtyAttributes#219]
I am currently trying to implement a dropdown menu for a list decorated with a reorderablelist.
As the dropdown menu would be part of an editor assembly, my first feeling that it would require another class (sibling or child of ReorderableListPropertyDrawer) to handle this menu. 

I have tried implementing it until I figured out that It relies on `SpecialCaseDrawerAttributeExtensions` to register special case drawers, but I can't add my own to this class's `_drawersByAttributeType` dictionary to be drawn in inspector

Maybe I'm implementing this drawer the wrong way though. Could you give me directions on how to implement this properly please?

**Comment by dbrizov** [comment]
All array types in Unity are reorderable out of the box since Unity **2020.2.x**. So my best bet is trying to create a decorator for each individual entry in the list itself
