### ISSUE TITLE
NaughtyAttributes doesn't work in StateMachineBehaviour

### ISSUE THREAD

**Issue by dbokser** [dbrizov/NaughtyAttributes#22]
NaughtyAttributes doesn't do anything when attached to attributes in a StateMachineBehaviour

`public class SetRandomParameter : StateMachineBehaviour {

    public string parameter;
                
    public enum ParameterType { integer, floatingPoint };
    [SerializeField]
    private ParameterType _parameterType;

    [ShowIf("IsInt")]
    public int min;
    [ShowIf("IsInt")]
    public int max;

    [ShowIf("IsFloat")]
    public Vector2 range;

    private bool IsInt()
    {
        return _parameterType == ParameterType.integer;
    }
    private bool IsFloat()
    {
        return _parameterType == ParameterType.floatingPoint;
    }

    // OnStateEnter is called when a transition starts and the state machine starts to evaluate this state
    override public void OnStateEnter(Animator animator, AnimatorStateInfo stateInfo, int layerIndex)
    {
            
    }
}`

![image](https://user-images.githubusercontent.com/2582947/42586504-e5e06c4c-84fd-11e8-8d9b-86bbee4e2c22.png)

**Comment by dbrizov** [comment]
The attributes implemented via **CustomPropertyDrawer** are now working. The custom ones like (Button, ReorderableList) aren't. The problem is that **OnEnable()** and **OnDisable()** methods of the **StateMachineBehviours** are not called. I don't know why :(

**Comment by Kotsuha** [comment]
Tested in Unity 2021.1.7f1

```
using System.Collections;
using System.Collections.Generic;
using NaughtyAttributes;
using UnityEngine;

namespace MakeSomething
{
    public class TestState : StateMachineBehaviour
    {
        public int Foo;

        [SerializeField]
        private int _bar;

        [ShowNonSerializedField] // Doesn't work
        private int _baz;

        [ReadOnly] // Doesn't work
        [SerializeField]
        private int _qux;
    }
}
```

**Comment by jnbbender** [comment]
Is there a reason why this was closed?
