### ISSUE TITLE
[Issue] ProgressBar with int not working

### ISSUE THREAD

**Issue by TheEmbracedOne** [dbrizov/NaughtyAttributes#222]
On the [website ](https://dbrizov.github.io/na-docs/attributes/drawer_attributes/progress_bar.html) the example of ProgressBar has an int value for max value, but it doesnt seem to work for me:

```csharp	
[Label("Filter Value")]
[ProgressBar("Filter Value", "ex_filter_max", EColor.Red)]
public int ex_filter_value;

public int ex_filter_max;
```
gives me: 
![image](https://user-images.githubusercontent.com/16197906/114244847-c54cb600-997e-11eb-8c18-1c12b05d4198.png)

but if I change the maxvalue to float:
```csharp	
[Label("Filter Value")]
[ProgressBar("Filter Value", "ex_filter_max", EColor.Red)]
public int ex_filter_value;

public float ex_filter_max;
```

it works; 
![image](https://user-images.githubusercontent.com/16197906/114244902-e31a1b00-997e-11eb-9a01-2d19cac306c4.png)

Is it possible to make the progress bar work with int? Or only float? 
Am I doing something wrong or is the documentation outdated?

(I have tried copying out that bit from the documentation and I get the same error:

```csharp
[ProgressBar("Stamina", "maxStamina", EColor.Green)] // Dynamic max value constructor
public int stamina = 150;

public int maxStamina = 200;
```

**Comment by dbrizov** [comment]
Fixed in faa02a1a2728620efc9e7453bbeaa15cb977a3c7
