### ISSUE TITLE
[Issue] Buttons are all grouped together regardless of order in code

### ISSUE THREAD

**Issue by glenneroo** [dbrizov/NaughtyAttributes#224]
public int var1;
[Button]
public void Func1() {}

public int var2;
[Button]
public void Func2() {}

In the Inspector, these will be shown in a different order:
var1
var2
<Button: Func1>
<Button: Func2>

I have tried putting them inside BoxGroup but methods are not allowed to be in BoxGroup.

**Comment by IF-ACT** [comment]
This seems not possible, in c# we can't get the order of members in a class.
But this is an interesting topic, I think there can be a meta attribute like this:
```c#
[Order(0)]
public int var1;

[Button, Order(1)]
public void Func1() {}

[Order(2)]
public int var2;

[Button, Order(3)]
public void Func2() {}
```
May consider to add this as a new feature. I'd like to submit a pull request for this.

**Comment by dbrizov** [comment]
That's intentional
