### ISSUE TITLE
[Issue] Inspector UI layout is broken in Unity 2020.3 when lists are inside a Serializable class

### ISSUE THREAD

**Issue by Oletus** [dbrizov/NaughtyAttributes#231]
Code to reproduce:

```
using System.Collections.Generic;
using UnityEngine;

[System.Serializable]
public class TestSerializable
{
    [SerializeField] private List<string> List1;
    [SerializeField] private List<string> List2;
}
```

```
using UnityEngine;
public class TestBehaviour : MonoBehaviour
{
    [SerializeField] private TestSerializable Foo;
}
```

Result:

![image](https://user-images.githubusercontent.com/453050/116676060-35af8b80-a9af-11eb-8d63-405d692a07af.png)

Reproduced this with NaughtyAttributes 2.0.9 and Unity 2020.3.6f1.

**Comment by dbrizov** [comment]
That's not caused by NaughtyAttributes. When there are no NA attributes used I am actually drawing the default inspector.
![image](https://user-images.githubusercontent.com/3619573/116678063-93dd6e00-a9b1-11eb-93df-a3df66296baa.png)

I also tested it with Unity 2021.1.4f1, and there is no issue on my end.
![image](https://user-images.githubusercontent.com/3619573/116678270-cb4c1a80-a9b1-11eb-82e0-731813f37828.png)

Can you test with the latest Unity version and tell me if that fixes it?

**Comment by Oletus** [comment]
Very odd, I have literally nothing else in the project than these scripts and I'm able to reproduce the issue even after deleting my Library folder and reimporting, but only if the NaughtyAttributes package is present - maybe some of my earlier reproduction attempts left some other cached data in an odd state? I'll try with **2021.1.5f1** as well.

**Comment by Oletus** [comment]
It looks like the issue doesn't reproduce with 2021.1.5f1, so maybe this is a bug on Unity's end. I wonder if there's any chance to make a workaround for the latest LTS? We weren't planning to move to a non-LTS version.

**Comment by IF-ACT** [comment]
Reproduced in Unity 2020.3.6f1c1, this issue is caused by Unity.

Test code (new project, without NaughtyAttributes):

```C#
// script Test.cs
using System.Collections.Generic;
using UnityEngine;

namespace DefaultNamespace
{
    public class Test : MonoBehaviour
    {
        [SerializeField] private TestSerializable Foo;
    }

    [System.Serializable]
    public class TestSerializable
    {
        [SerializeField] private List<string> List1;
        [SerializeField] private List<string> List2;
    }
}
```

```C#
// script MyEditor.cs
using UnityEditor;
using UnityEngine;

[CustomEditor(typeof(Object), true)]
public class MyEditor : Editor
{
}
```

The script doesn't do any thing, but issue still exists. Please consider send this issue to Unity official.
