### ISSUE TITLE
Expandable Attribute doesn't work in described situation

### ISSUE THREAD

**Issue by NudeNULL** [dbrizov/NaughtyAttributes#232]
Unity Version: 2019.4.24f1
Naughty Attributes: 2.0.9

Steps to reproduce:

Create a Scriptable Objects Array like this:
1. Create a class that inherits scriptable object with Create asset menu attribute (ClassA)
2. Create a few file of this instance in unity project
3. Create another class that inherits from scriptable object with create asset menu attribute (ClassB)
4. Add to this class also a field of type [SerializeField] [Expandable] private List<ClassA> instances;
5. In Unity drag and drop the instances of ClassA into List
6. You will get some errors

**Comment by dbrizov** [comment]
Fixed in e4edd04d78aeb27cb99134b8fc84f521485de6de
