### ISSUE TITLE
[Request] ButtonAttribute support for methods in nested objects.

### ISSUE THREAD

**Issue by pawelsalwa** [dbrizov/NaughtyAttributes#233]
ButtonAttribute supports methods placed in `MonoBehaviour `and `ScriptableObject` derived classes (custom Editor).
But if `MonoBehaviour` class has field which type is marked as `[Serializable]` and this type has a method marked with `ButtonAttribute` then Button doesn't show. 
Custom base property drawer that supports ButtonAttribute would be useful (is it even possible?). Thank you very much!

**Comment by pawelsalwa** [comment]
I definitely believe you. Customizing property drawers can be hell :]

**Comment by dbrizov** [comment]
There is an issue for that request already: #107
