### ISSUE TITLE
[Request] Foldout end section

### ISSUE THREAD

**Issue by Seshua** [dbrizov/NaughtyAttributes#234]
Hello dbrizov Team

If possible make a function for foldout so we can do something like this
Thanks for consideration.

[Foldout.Start("Stats")]
public float health
public float damage
public float speed
[Foldout.End("Stats")]

Instead of 

[Foldout("Stats")]
public float health
[Foldout("Stats")]
public float damage
[Foldout("Stats")]
public float speed

**Comment by dbrizov** [comment]
There is already a request for this: #196
