### ISSUE TITLE
Adding package.json for Package manager

### ISSUE THREAD

**Issue by Zen12** [dbrizov/NaughtyAttributes#238]
I have a template project and NaightyAttributes are part of it. It would be great to install NaughtyAttributes via PackageManger. Unity PlackageManger requires package.json (here is more info: https://docs.unity3d.com/Packages/com.unity.package-manager-ui@1.8/manual/index.html)

Thanks

**Comment by dbrizov** [comment]
You can install NA with the package manager. Check out the **Installation** section in the docs or the README.md
