### ISSUE TITLE
InfoBox not working on nested class

### ISSUE THREAD

**Issue by Dliix66** [dbrizov/NaughtyAttributes#244]
Hello, here is an example:

```
using System;
using NaughtyAttributes;
using UnityEngine;

public class TestClass : MonoBehaviour
{
	[InfoBox("Working box")]
	public int myInt;

	[InfoBox("Working box 2", InfoBoxType.Warning)]
	public NestedTestClass nestedTestClass;
	
	[Serializable]
	public class NestedTestClass
	{
		[InfoBox("Not working box")]
		public int myInt2;
	}
}
```

<img width="328" alt="Capture d’écran 2021-06-25 à 14 43 43" src="https://user-images.githubusercontent.com/2865871/123426472-beb7fd00-d5c3-11eb-80f0-1834e98f244d.png">

Thanks again for the hard work ! 🙏🏻

**Comment by dbrizov** [comment]
You need to use the [AllowNesting](https://dbrizov.github.io/na-docs/attributes/special_attributes/allow_nesting.html) attribute in this case.
