### ISSUE TITLE
Some attributes stop working when Unity restarts

### ISSUE THREAD

**Issue by Medallyon** [dbrizov/NaughtyAttributes#246]
Unity version: 2020.3.0f1

I was wondering what was happening, why my objects would sometimes have missing inspector attributes. I figured out that attributes like the ButtonAttribute, ShowIf/HideIf, and more, would not appear after restarting Unity with my project.

![image](https://user-images.githubusercontent.com/17483199/124260005-16f08100-db27-11eb-9625-d7c9f79a78a9.png)
![image](https://user-images.githubusercontent.com/17483199/124260008-1821ae00-db27-11eb-9d27-59116eb2fa02.png)

Other attributes work as intended after a restart:
![image](https://user-images.githubusercontent.com/17483199/124259967-0d671900-db27-11eb-9d4a-7418c1ffb2d7.png)

It all works fine again after removing the NaughtyAttributes folder from Assets and reimporting it through the Package Manager. But as soon as I boot up the project again the next day, the Attributes stop working again.

What could be causing this? How would I fix this? Thanks in advance.

**Comment by Medallyon** [comment]
P.S. I use the iTween & MyBoxAttributes plugins, although I don't believe they should be interfering with one another. Please correct me if I'm wrong.

**Comment by arimger** [comment]
I'm pretty sure you have a conflict since both NaughtAttributes and MyBox are based on the same functionality - overriding the base Editor class for all UnityEngine.Objects.

**Comment by dbrizov** [comment]
I tested it, and it's everything seems to work on my end. @arimger is probably right, MyBoxAttributes are probably overriding the base Editor class.
