### ISSUE TITLE
I can't pay you 🗡️ 

### ISSUE THREAD

**Issue by rainbowcreatures** [dbrizov/NaughtyAttributes#251]
It says merchant account restricted, tried both PayPal and the coffee thing. Trying from Czech Republic.

**Comment by dbrizov** [comment]
Hmm, I don't know. Don't worry about it. I am glad you like the plugin.
Thanks for trying :)

Cheers!

**Comment by rainbowcreatures** [comment]
Ok :) Yeah great idea, I was looking for something like this specifically, couldn't believe the basic tags are so limited and you need to create custom inspectors and learn all of that stuff just for the basics (like the ones you provide)... Closing this, but if you ever find out feel free to re-open and I'll donate :) Take care!
