### ISSUE TITLE
[Issue] Dropdown does not set prefab dirty if editing outside prefab mode

### ISSUE THREAD

**Issue by JonLevin25** [dbrizov/NaughtyAttributes#258]
Repro:
1. Put the component below on a prefab
2. **don't enter prefab mode* - just select it in the project window
3. Change the dropdown value
Expected - sets the prefab dirty
Actual - doesn't (saving will not save changes)

Additional:
- Changing value in `dummyEnum` (using Unity's native dropdown impl) - does set the prefab dirty
- Double click prefab to enter prefab mode - the dropdown will now set dirty properly

```c#
using NaughtyAttributes;
using UnityEngine;

public class TestNaughtyBug : MonoBehaviour
{
    public enum DummyEnum
    {
        A,
        B,
    }

    [SerializeField] private DummyEnum dummyEnum;
    [SerializeField, Dropdown(nameof(dropdownOptions))] private string myDropdown;
    
    private static string[] dropdownOptions =
    {
        "DEFAULT",
        "A",
        "B",
    };
}

```

I could maybe fix this myself if you point me in the right direction - not sure what it's called to edit the prefab root without entering prefab mode - which makes it hard to google.

**Comment by dbrizov** [comment]
I will fix it, don't worry. There was some code that manages prefab mode, and scene mode for the button attribute. There was some `DrawButton` code or something, I don't remember exactly.

**Comment by dbrizov** [comment]
I think I found it
```csharp
PrefabStage stage = PrefabStageUtility.GetCurrentPrefabStage();
if (stage != null)
{
	// Prefab mode
	EditorSceneManager.MarkSceneDirty(stage.scene);
}
else
{
	// Normal scene
	EditorSceneManager.MarkSceneDirty(EditorSceneManager.GetActiveScene());
}
```

**Comment by JonLevin25** [comment]
Cool, I see that's in the Button method.
Assume you mean to implement it for dropdown/other needed places as well?

I don't think it will work though - since in the situation I'm talking about the prefab is **not** in the scene - it's a prefab highlighted in the project window. It will  also mark the scene dirty.

Looking at Unity's (mess of an) API, it seems like this might help:
`PrefabUtility.GetPrefabAssetType(((UnityEngine.Object)target))` (Returns `NotAPrefab`, `Regular`, `Variant` etc)
You do have to cast to Unity Object to use the method, which I think is appropriate since `target` from the SerializedObject, right?

P.S. Perhaps this is also a sleeper bug with the Button implementation / other places?

**Comment by dbrizov** [comment]
I tested it with Unity 2021.1.20f1, and the dropdown marks the scene as dirty. Can you confirm this? Also, can you tell which Unity version you are using?

**Comment by dbrizov** [comment]
Cannot reproduce
