### ISSUE TITLE
[Bug] Unity Lists and Padding not rendering when Naughty Attributes package is installed.

### ISSUE THREAD

**Issue by Gohloum** [dbrizov/NaughtyAttributes#274]
Below link is a zip of a simple project for Unity 2021.1.19f1 with Naughty Attributes installed. 

To see error, go to sample scene and expand canvas
Click on Listtest object and look at attached script, you will notice there are 7 indexes and no rendering for the indexes.
Click on GridLayout.  Expand the padding drop down and you will see no padding fields rendering.

Link - https://tangerinepop.com/Unity/NARenderBug.zip

**Comment by dbrizov** [comment]
Related to #267

**Comment by Gohloum** [comment]
Yes.  Was the zip package helpful?  Also, I am on a windows 10 box. I just got my mac back from the shop and I need to reinstall Unity, but I can test it on that machine as well if you need me to.

**Comment by Gohloum** [comment]
I found another related issue which I assume to be similar to the padding expandable group.  I just tried adding a Edge 2D Collider to an object and the Points expandable group is behaving in the same manner.  Maybe these are related to the Expandable tag?

**Comment by dbrizov** [comment]
It's related to #281. I tested it with Unity 2021.2.10f1, and can't reproduce it
