### ISSUE TITLE
Make [ShowNonSerializedField] variables into standard format

### ISSUE THREAD

**Issue by xsduan** [dbrizov/NaughtyAttributes#279]
Currently, `[ShowNonSerializedField]` takes the variable name literally. This isn't too big of a deal as I use it for debug anyways so having a bit of rogue labels isn't a huge deal for me, but just for consistency it should use the standard [ObjectNames.NicifyVariableName](https://docs.unity3d.com/ScriptReference/ObjectNames.NicifyVariableName.html) (btw, who came up with that name lol).

Example:
![image](https://user-images.githubusercontent.com/9505910/140683187-5aa4bfde-f59c-48c9-8c47-0f16523f5c3b.png)

**Comment by rhys-vdw** [comment]
Looks like this would be a one line change: https://github.com/dbrizov/NaughtyAttributes/blob/0c4ba8067f824d7246a8e605bbbb6360edcf551a/Assets/NaughtyAttributes/Scripts/Editor/Utility/NaughtyEditorGUI.cs#L238

**Comment by dbrizov** [comment]
Fixed in 4f07279066349a5c42bf097a3d2edb76883fb367
