### ISSUE TITLE
Buttons cannot be used on multiple objects at once

### ISSUE THREAD

**Issue by sleepandpancakes** [dbrizov/NaughtyAttributes#28]
When I select multiple gameobjects with the same component that uses a [Button] attribute, pressing the button only executes the function on the first gameobject instead of all of them.

**Comment by dbrizov** [comment]
I don't know how to fix this one, unfortunately. I am just using Unity's API.

**Comment by Manuel-Meyer** [comment]
Well you could use serializedObject.targetObjects and Invoke the method on every object.

call the Buttonmethod with targetObject**s**
`NaughtyEditorGUI.Button(serializedObject.targetObjects, method);`

and change the Buttonmethod to
`public static void Button(UnityEngine.Object[] target, MethodInfo methodInfo)
		{
			bool visible = ButtonUtility.IsVisible(target[0], methodInfo);
			if (!visible)
			{
				return;
			}

			if (methodInfo.GetParameters().All(p => p.IsOptional))
			{
				ButtonAttribute buttonAttribute = (ButtonAttribute)methodInfo.GetCustomAttributes(typeof(ButtonAttribute), true)[0];
				string buttonText = string.IsNullOrEmpty(buttonAttribute.Text) ? ObjectNames.NicifyVariableName(methodInfo.Name) : buttonAttribute.Text;

				bool buttonEnabled = ButtonUtility.IsEnabled(target[0], methodInfo);

				EButtonEnableMode mode = buttonAttribute.SelectedEnableMode;
				buttonEnabled &=
					mode == EButtonEnableMode.Always ||
					mode == EButtonEnableMode.Editor && !Application.isPlaying ||
					mode == EButtonEnableMode.Playmode && Application.isPlaying;

				bool methodIsCoroutine = methodInfo.ReturnType == typeof(IEnumerator);
				if (methodIsCoroutine)
				{
					buttonEnabled &= (Application.isPlaying ? true : false);
				}

				EditorGUI.BeginDisabledGroup(!buttonEnabled);

				if (GUILayout.Button(buttonText, _buttonStyle))
				{
                    foreach (var t in target)
                    {
						object[] defaultParams = methodInfo.GetParameters().Select(p => p.DefaultValue).ToArray();
						IEnumerator methodResult = methodInfo.Invoke(t, defaultParams) as IEnumerator;
					

						if (!Application.isPlaying)
						{
							// Set target object and scene dirty to serialize changes to disk
							EditorUtility.SetDirty(t);

							PrefabStage stage = PrefabStageUtility.GetCurrentPrefabStage();
							if (stage != null)
							{
								// Prefab mode
								EditorSceneManager.MarkSceneDirty(stage.scene);
							}
							else
							{
								// Normal scene
								EditorSceneManager.MarkSceneDirty(EditorSceneManager.GetActiveScene());
							}
						}
						else if (methodResult != null && t is MonoBehaviour behaviour)
						{
							behaviour.StartCoroutine(methodResult);
                        
						}
                    }
				}

				EditorGUI.EndDisabledGroup();
			}
			else
			{
				string warning = typeof(ButtonAttribute).Name + " works only on methods with no parameters";
				HelpBox_Layout(warning, MessageType.Warning, context: target[0], logToConsole: true);
			}
		}`

kind of hacky and would need some love ;-)
