### ISSUE TITLE
[Bug] Unity 2021.1.28 + problems with rendering "List"

### ISSUE THREAD

**Issue by MaksimNarchuk** [dbrizov/NaughtyAttributes#281]
Hello. This is a simple code for reproducing problems.
```
using System;
using System.Collections.Generic;
using NaughtyAttributes;
using UnityEngine;

public class Test : MonoBehaviour
{
    [SerializeField] private List<string> listA;
    [NonReorderable, SerializeField] private List<string> listB;
    [ReorderableList, SerializeField] private List<string> listC;

    [SerializeField] private Inner inner;
}

[Serializable]
public class Inner
{
    [SerializeField] private List<string> listA;
    [NonReorderable, SerializeField] private List<string> listB;
    [ReorderableList, SerializeField] private List<string> listC;
}
```
<img width="944" alt="Screenshot at Nov 09 17-10-39" src="https://user-images.githubusercontent.com/24695927/140939285-b8f91a0c-bd87-4458-adbb-97c3aa2295ca.png">
<img width="942" alt="Screenshot at Nov 09 17-11-46" src="https://user-images.githubusercontent.com/24695927/140939507-532bf48f-8cff-4427-b193-61c4c7155153.png">

Previously, this was reproduced only in a large project
But now it is reproduced even in an empty project
I could not find any dependencies on other Unity components or plugins. It's probably a problem of theirs.
But why doesn't the attribute [ReorderableList] in class "Inner" work?

**Comment by MaksimNarchuk** [comment]
Here are some assets that could theoretically affect behavior
[assets third party.zip](https://github.com/dbrizov/NaughtyAttributes/files/7505391/assets.third.party.zip)
.

**Comment by MaksimNarchuk** [comment]
I also want to note that Unity 2021.1.28 should display fields with the type "List" as a field with your "ReorderableList" attribute. 
I could observe this in a clean project for a while. But literally after a few minutes of working with other assets, the behavior of the editor became like in the screenshots.

**Comment by rhys-vdw** [comment]
Are lists not reorderable in 2020+ anyway?

**Comment by MaksimNarchuk** [comment]
Hi all. I have taken more time with this problem and noticed that the problem is not constant. And now I'm sure it's a bug of Unity - the exact same behavior was noted in a blank project.

<img width="1187" alt="image" src="https://user-images.githubusercontent.com/24695927/143575680-0be9f938-9fa2-4df0-b8a0-062f0931802a.png">

**Comment by reptille** [comment]
have the same bug, but only on the second monitor
![Снимок экрана 2021-12-09 в 11 49 44](https://user-images.githubusercontent.com/25555387/145363973-450437e1-14be-40e9-a032-c9b5fcef68b8.png)
r

**Comment by VGMFR** [comment]
Same thing, it happens only on my second or third screen which makes absolutely no sense :')
Version: Unity 2021.1.28f1, was fine on 2023 LTS.
I hope this will get fix in the next release, as it's a bit annoying!

**Comment by dbrizov** [comment]
Just tested with 2021.2.10f1 and it no longer happens.
