### ISSUE TITLE
[Bug] Buttons (and a lot of other attributes) not working in Unity 2020.3 LTS

### ISSUE THREAD

**Issue by jessyrobinson** [dbrizov/NaughtyAttributes#285]
Cannot render buttons on any script.

**Comment by phamtanlong** [comment]
Same issue, waiting for solutions

**Comment by Pool3ChristianHolzer** [comment]
Same here, the variable name is not rendered for [ShowIf] for example.

**Comment by dbrizov** [comment]
Just downloaded the latest 2020.3 LTS, and the issue no longer accurs

**Comment by Podden** [comment]
I'm mostly missing the [ValidateInput](https://github.com/dbrizov/NaughtyAttributes#validateinput) system.
