### ISSUE TITLE
[Improvement] Unnecessary DLL in Build output

### ISSUE THREAD

**Issue by Fijo** [dbrizov/NaughtyAttributes#287]
I'm using this library via openupm in my game and am quite happy with being able to do that.
There is however one thing that bugs me a little:
I can't prevent the **NaughtyAttributes.Test.dll** from landing in the build output of my game even though I'm never using any of it. It's only required for the Samples which I am not using.

I briefly tried to fix this using either checkboxes within the "NaughtyAttributes.Test"-AssemblyDefinition or moving the sources to the sample folder. I didn't manage to solve it doing that and that's why I decided to open this Issue instead of just creating a PR.

**Comment by dbrizov** [comment]
Just made a build, and it's really going into the build. I need to see why.

**Comment by dbrizov** [comment]
If I mark the **NaughtyAttributes.Test.asmdef** as an Editor .dll, then it doesn't go into the build. However, in this case the test scripts don't work, because I can't attach them to game objects. What bugs me is that the .dll goes into the build even if nothing is referencing it. The other solution is to not include the Test folder into the plugin, but then the samples scene will be gone, and I don't want to do that. If you want to get rid of the .dll in the builds that badly, I guess your only option is to download the plugin via the Asset Store, and delete the Test folder.

**Comment by rhys-vdw** [comment]
[There is a solution](https://forum.unity.com/threads/editor-only-monobehaviour.508844/#post-3322419) that achieves what you want: Tag the GameObjects as "EditorOnly" and then you can attach MonoBehaviours from the editor asmdef. You can apply this tag to every object in the sample scene.

![image](https://user-images.githubusercontent.com/822105/142789211-53a23a04-ef8b-4012-93e4-5a2f642a6b4e.png)

**Comment by rhys-vdw** [comment]
Scratch my last message. I did find a nice solution though that supports distributing the test scene as well as convenient editing when working with this project directly. See #288

**Comment by rhys-vdw** [comment]
@dbrizov would you be open to an amended upm release action that renames `Samples` to `Samples~` just in the upm branch? I feel like that's probably the cleanest solution, allowing users to import them into their project to play around but not including it in builds by default.

**Comment by dbrizov** [comment]
@rhys-vdw  If I rename it to `Samples~`, people won't be able to see them in the editor when they import them.
I want to try a different solution.
Check this #291

**Comment by rhys-vdw** [comment]
So a common pattern is to rename to `Sample~` only in the release branch (upm branch). That way when you clone the repository it's all there. When you import the project from upm unity adds a button in the package manager to import the samples into your project if you want them (even if the folder is suffixed with `~`).

See [favoyang's explanation](https://medium.com/openupm/how-to-maintain-upm-package-part-1-7b4daf88d4c4#236a):

> One solution is that keep the folder Samples in version control while using a CI to rename it to Samples~. Your package.json shall remain no change.

This seems like the perfect solution for NA. it would just be a small change to your release action.

**Comment by rhys-vdw** [comment]
Example from 2D Pixel Perfect Camera

![image](https://user-images.githubusercontent.com/822105/152894504-cc752004-4999-4e17-81a9-49a563e16cdc.png)
![image](https://user-images.githubusercontent.com/822105/152894512-771443cb-6574-44c3-b044-297b56c343af.png)
![image](https://user-images.githubusercontent.com/822105/152894552-38f2b927-b1c4-4bf5-a90a-5ce04849c566.png)
