### ISSUE TITLE
[Issue] Showif is not work with Editor class

### ISSUE THREAD

**Issue by threerabbitgames** [dbrizov/NaughtyAttributes#290]
ShowIf in A.cs does not work when A.cs is referenced as CustomEditor in another editor class.

**Comment by dbrizov** [comment]
Can you show me the exact example?

**Comment by threerabbitgames** [comment]
> Can you show me the exact example?

sure i can show you
![1](https://user-images.githubusercontent.com/68151652/146310896-8cec1f7a-ceb3-435c-ab15-9e8dbf9a5ede.png)
![2](https://user-images.githubusercontent.com/68151652/146310899-d2d15eed-020d-459a-a0e2-03c1973039b1.png)
![3](https://user-images.githubusercontent.com/68151652/146310906-be5ffc08-107c-42d6-8000-502b93284790.png)
![4](https://user-images.githubusercontent.com/68151652/146310909-9d14234b-e4a7-40ca-abcd-4113a0697367.png)

**Comment by threerabbitgames** [comment]
experimenting to solve the problem
1. base.OnInspectorGUI();
2. DrawDefaultInspector();
3. [System.Serializable] public enum Type { C1, C2,C3 } 

but.. not work ㅠ_ㅠ..

**Comment by IF-ACT** [comment]
Try `[ShowIf("type", Type.Case1)]`

**Comment by dbrizov** [comment]
Your editor needs to inherit from `NaightyInspector.cs` if you want to use NA'a attributes
