### ISSUE TITLE
MeshFilter components not drawn

### ISSUE THREAD

**Issue by WazWaz** [dbrizov/NaughtyAttributes#3]
MeshFilter components are somehow broken by InspectorEditor. The mesh is not shown:

![2017-10-23](https://user-images.githubusercontent.com/7268071/31867998-2e8bd2c8-b7dc-11e7-9934-69da96708e77.png)

**Comment by WazWaz** [comment]
Workaround is to insert the following at start of InspectorEditor.OnInspectorGUI():

`            if (this.target as MeshFilter) {
                DrawDefaultInspector();
                return;
            }
`

**Comment by dbrizov** [comment]
Thanks mate. I fixed it more globally. All unity scripts don't have NaughtyAttributes. In that case I use the default inspector.
```
if (fields.All(f => f.GetCustomAttributes(typeof(NaughtyAttribute), true).Length == 0))
{
    this.DrawDefaultInspector();
}
```
