### ISSUE TITLE
Unity Asset Store

### ISSUE THREAD

**Issue by supersaiyansubtlety** [dbrizov/NaughtyAttributes#30]
Hello, 
I absolutely love this package, it's super useful for quickly making user-friendly inspectors for classes! Most of these attributes should be built into Unity. 

But why isn't this on the asset store? It took me a while to find it (through unitylist.com).

**Comment by dbrizov** [comment]
There you go mate.
[AssetStore](https://assetstore.unity.com/packages/tools/gui/naughtyattributes-129996)

**Comment by supersaiyansubtlety** [comment]
Awesome!
Thanks so much
