### ISSUE TITLE
ReorderableList doesn't work on multiple components with the same variable name in the same GameObject

### ISSUE THREAD

**Issue by PvtPrivate** [dbrizov/NaughtyAttributes#32]
Any other ReorderableList with the same variable name will use the first component's value instead of its own component's value.

![image](https://user-images.githubusercontent.com/16520813/47063686-6d49f400-d206-11e8-92cf-7165b896e800.png)
In that example, duplicate components will use the first component's values.

**Comment by dbrizov** [comment]
Fixed
