### ISSUE TITLE
[Request] Scriptableobject attribute

### ISSUE THREAD

**Issue by IceSentry** [dbrizov/NaughtyAttributes#33]
This thread shows a few attributes related to using scriptableobjects nested in monobehaviours

https://forum.unity.com/threads/editor-tool-better-scriptableobject-inspector-editing.484393/

Consider adding something like this to your package

**Comment by MingFengShang** [comment]
+1

**Comment by dbrizov** [comment]
Guys, what do you think about this?
Should I make an attribute, or make a custom inspector for scriptable objects, so that they can be collapsed/uncollapsed by default?

**Comment by dbrizov** [comment]
Implemented in abf930678a848c310d9c927dd11305afef0f5f4d

I decided to make it an attribute for consistency, and because many people are using custom property drawers for scriptable objects.
