### ISSUE TITLE
Some features down't work correctly

### ISSUE THREAD

**Issue by Anti-Ded** [dbrizov/NaughtyAttributes#347]
Hello. Installed this plugin to my project, but something wrong(

there is no method button
![27 12 2022 16 59 25](https://user-images.githubusercontent.com/67957247/209677720-8753f908-cc3a-4d78-b962-5e7e4e386bc3.png)

No foldout, enabledif or showif(
![27 12 2022 17 00 05](https://user-images.githubusercontent.com/67957247/209677785-9da431c8-420b-42c7-9b33-ee01adb3e5f4.png)
![27 12 2022 17 00 11](https://user-images.githubusercontent.com/67957247/209677821-ca5d643e-fc14-4ebf-895e-e9b984fb76cb.png)
![27 12 2022 17 00 14](https://user-images.githubusercontent.com/67957247/209677830-db0e8d44-9d1c-425e-9e4a-2560ace66145.png)

readonly works only for nested items
![27 12 2022 17 00 20](https://user-images.githubusercontent.com/67957247/209677910-4d518b78-bcad-4518-9c35-dc80a962b5fc.png)
 please help

**Comment by DeepChallengerVR** [comment]
Post a full log of your debug console.

**Comment by Anti-Ded** [comment]
Simple Note plugin conflict found. 
Just look at all Editor folders in project to check useless and useful items.
Thanks a lot) Great plugin!
