### ISSUE TITLE
Reorderable List doesn't work with an array of structs/classes

### ISSUE THREAD

**Issue by the-mr-matt** [dbrizov/NaughtyAttributes#36]
I have a struct `Keybind` and an array of `Keybinds` shown below. 

        [System.Serializable]
        public struct Keybind
        {
            public string Id;
            public KeyCode KeyCode;
        }
        
        [ReorderableList, SerializeField] protected Keybind[] m_Keybinds;

However, it is not showing in the inspector when I use the ReorderableList attribute: [Screenshot](https://imgur.com/a/YUFVHzm)

**Comment by FaizanDurrani** [comment]
This should fix this.
https://gist.github.com/FaizanDurrani/8a3da0f5ef08a24e6ef10efcac62e45e (specifically line 34, IIRC)

Would like it if it got fixed in the repo though.

**Comment by the-mr-matt** [comment]
Any ideas for making nested reorderable lists work?

**Comment by D3m0n92** [comment]
Same needs...

**Comment by D3m0n92** [comment]
> This should fix this.
> https://gist.github.com/FaizanDurrani/8a3da0f5ef08a24e6ef10efcac62e45e (specifically line 34, IIRC)
> 
> Would like it if it got fixed in the repo though.

Works!

**Comment by dbrizov** [comment]
Thanks for the fix, I updated the repo.
