### ISSUE TITLE
ResizableTextArea not work in unity 2017.4.16

### ISSUE THREAD

**Issue by rinnocenti** [dbrizov/NaughtyAttributes#38]
ResizableTextArea not work in strings and array strings.

**Comment by dbrizov** [comment]
Yeah, in 2018.3.0 too. Unfortunately, I don't know how to fix it, because I am using EditorGuiLayout.TextArea, and it's just not working the same as before.

**Comment by dbrizov** [comment]
Check 2019.1. It started working again on my end again. They probably fixed some bug.
