### ISSUE TITLE
[Bug] - Overridden methods in derived classes generate multiple buttons

### ISSUE THREAD

**Issue by SimplicisMirificus** [dbrizov/NaughtyAttributes#383]
Hello! I am unsure if this project is still actively being maintained, but I wanted to post this issue here because I couldn't find anything resembling it during my brief internet searching. If anyone has encountered this or found a workaround for this, I'd be much appreciative to know.

Take the following code for example:

```c-sharp
// Base.cs
[NaughtyAttributes.Button("Do Button Clicked")]
protected virtual void Editor_ButtonClicked() => Debug.Log("Clicked Base Class!");

// Derived.cs
protected override void Editor_ButtonClicked() => Debug.Log("Clicked Derived Class!");
```

* Ignore typos, if there are any; just assume the code is correct. I did it here in the GitHub text box :)

**Expected results:**
When placing either the Base or the Derived component on a game object, only one button is shown.

**Actual results:**
When placing the Base component on a game object, only one button is shown.
When placing the Derived component on a game object, two buttons are shown.

**Comment by TylerTemp** [comment]
I think this is [a known open issue](https://github.com/dbrizov/NaughtyAttributes/issues/292), though it has a reference said it's fixed.

NaughtyAttributes has many forks and some might have this issue fixed. But as no fork stands-out to replace this upstream version, I have no idea which to choose.

Though [I have a separated project](https://github.com/TylerTemp/SaintsField/?tab=readme-ov-file#button) which has all the functions of NA and some extra tools. I use it on my own projects & my company's projects.

If you're interested you can have a try. But, using `Button` (meta attributes) requires an editor level component, which means you WILL need to migrate, and take the potential problems it has

Most APIs are the same as NaughtyAttributes but some still requires some changes.

```csharp
public class BaseM : MonoBehaviour
{
    [Button("Do Button Clicked")]
    protected virtual void Editor_ButtonClicked() => Debug.Log("Clicked Base Class!");
}

public class Derived : BaseM
{
    protected override void Editor_ButtonClicked() => Debug.Log("Clicked Derived Class!");
}
```

![A 86T(DLR_3VI9LXHWAQ@`H](https://github.com/dbrizov/NaughtyAttributes/assets/6391063/a263cb5c-f0e9-4dee-87d2-ea37c33d0264)

**Comment by SimplicisMirificus** [comment]
Ok. I'll give those a look. I'll go ahead and close this issue; since it is a duplicate. Many thanks!
