### ISSUE TITLE
Can not use attributes in a serializable class and using the list of that class.

### ISSUE THREAD

**Issue by imranarif011** [dbrizov/NaughtyAttributes#42]
I want to use "ShowIf" & "OnValueChange" on a single variable that is not currently being usable in Unity 2017.2.17

**Comment by dbrizov** [comment]
OnValueChange is only executing some code when the value of a property changes. What exactly do you want to achieve?

**Comment by imranarif011** [comment]
Actually I have scenario. I am creating a list of serializeable class objects. And I want to show different variables on enabling different variables.

Like here:

[System.Serializable]
public class Sound
{
    public string soundName;

    public enum SoundCategories
    {
        Sound,
        Music
    }

    public SoundCategories soundCategories;

    // If this option is selected, I want to show only the clips variable and hide
    // volume and pitch variable.
    public bool onlyClips;

    public AudioClip[] clips;

    [Range(0f, 1f)]
    public float volume;

    [Range(0.1f, 3f)]
    public float pitch;

}

public List<Sound> sounds = new List<Sound>();

I have tried "ShowIf" in this situation but this is not working. Kindly Help

**Comment by dbrizov** [comment]
Unfortunately nesting is not supported. There is already an issue about that. A lot of people are complaining. I need to refactor the whole thing, because with the current system it's not possible. I just haven't found the time to do so.

**Comment by ReGaSLZR** [comment]
> Unfortunately nesting is not supported. There is already an issue about that. A lot of people are complaining. I need to refactor the whole thing, because with the current system it's not possible. I just haven't found the time to do so.

Hi, @dbrizov Any chance this is planned to be worked on sometime in the future?
