### ISSUE TITLE
ArgumentException spam

### ISSUE THREAD

**Issue by BradenRobertsL** [dbrizov/NaughtyAttributes#47]
Everything in the inspector is working fine all the attributes are working and it doesn't prevent me from running my game but every time the project compiles my console gets spammed with the following
![image](https://user-images.githubusercontent.com/19561904/54096899-b5b2ba00-4412-11e9-8d08-e3cff9871c47.png)
I've tried to remove all the attributes and pinpoint whats causing it but whether I'm using attributes or not these errors are always spammed to the console.

**Comment by dbrizov** [comment]
ok mate, thanks. I made some updates yesterday, maybe I broke something.
Will check it out today.

**Comment by dbrizov** [comment]
```this.script = this.serializedObject.FindProperty("m_Script");```
This line is the problem. Are you deriving from **MonoBehaviour** or **ScriptableObject**. I don't know how to reproduce it.

**Comment by dbrizov** [comment]
Can you tell me the exact case? What attribute you are using? If you can give me the whole script that will help a lot. I don't need the methods, only the members with attributes.
