### ISSUE TITLE
Slider is disabled if we add a Label

### ISSUE THREAD

**Issue by YetiYetYet** [dbrizov/NaughtyAttributes#51]
Hi dbrizow,
I love this plugins and i love you <3 <3 ! thanks a lot for your work !
I found a little bug i think.

When you add a label and a slider, the slider is disabled...
Maybe you can correct it when you have some time  ?
And will you marry me ?

![image](https://user-images.githubusercontent.com/20752352/55620204-95201a80-579a-11e9-95df-49f86e86d31b.png)

**Comment by dbrizov** [comment]
Thanks Alexis,
I will fix it in the weekend :)

**Comment by Jordy3D** [comment]
Similar thing seems to happen with ShowAssetPreview as well.

**Comment by dbrizov** [comment]
Fixed in version 2.0.0
