### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by tobiasweger** [dbrizov/NaughtyAttributes#53]

**Comment by MostHated** [comment]
Awesome issue report man. Extremely helpful. I am sure they will get right to it.

**Comment by dbrizov** [comment]
@MostHated For some reason the description is not on github, but I got it on my email

> When I try to add an attribute like this, it doesn't work.

> using UnityEngine;
> using NaughtyAttributes;

> public class Test : MonoBehaviour
> {
>    [Label("P")]
>    public int i;

    
>    void Start()
>    {
       
>    }
> }
> I've imported Naughty Attributes from the AssetStore and clicked on "Update Attributes Database" but my Attributes won't work. What am I doing wrong?

You don't have to press the **Update Attributes Database**. What version of Unity are you using?

**Comment by Chifilly** [comment]
I'm having the same issue. I want to use a MinMaxSlider but it's just showing as a basic Vector2 input. I'm using Unity version 2019.1.0f2

**Comment by rhys-vdw** [comment]
@BenedictWilkins this issue is closed, just create a new one with an appropriate title.
