### ISSUE TITLE
[Issue] ReorderableList has compatibility issue with AssetReference

### ISSUE THREAD

**Issue by bitinn** [dbrizov/NaughtyAttributes#54]
```
        [SerializeField]
        [ReorderableList]
        private List<AssetLabelReference> _BuildModeAssetLabels = null;
```

<img width="293" alt="Screen Shot 2019-04-08 at 11 28 17" src="https://user-images.githubusercontent.com/1484279/55696902-a4e56c00-59f1-11e9-9b25-d007e65af39b.png">

Result in a very nice looking UI, but is not actually usable, in that clicking on the dropdown menu has no effects:

Not sure this can be fixed on the NaughtyAttributes side or not. So far removing `[ReorderableList]` is the only workaround.

**Comment by dbrizov** [comment]
I need to check that. Haven't used **AssetLabelReferences** before. Don't even know what it's for.

**Comment by dbrizov** [comment]
Since Unity **2020.2.x** all lists are reorderable by default. You no longer have to use the ReorderableList attribute.
