### ISSUE TITLE
ReorderableList doesn't work right with complex elements

### ISSUE THREAD

**Issue by RunninglVlan** [dbrizov/NaughtyAttributes#57]
I have a list of custom objects
```
public class Points : ScriptableObject {
    [ReorderableList] public List<Point> value = new List<Point>();
    [Serializable] public struct Point {
        public string name;
        public Vector3 position;
        ...
    }
}
```
It shows up as follows.
![image](https://user-images.githubusercontent.com/11376741/56638705-88933180-6677-11e9-9247-47f660add810.png)
I can't expand elements anymore. And reordering them is difficult, as Foldout is rendered on top of reordering button.

**Comment by ReGaSLZR** [comment]
I just ran into the same issue (only difference is... the variables don't even show at all on my end).
@RunninglVlan , did you find a solution to temporarily fix this on your project?

**Comment by RunninglVlan** [comment]
Nope, I hoped it would be fixed in the library, but this doesn't seem to be happening 😅
