### ISSUE TITLE
InspectorFoldoutGroup

### ISSUE THREAD

**Issue by smkplus** [dbrizov/NaughtyAttributes#59]
Please Add Foldout like this

https://github.com/dimmpixeye/InspectorFoldoutGroup

![](https://camo.githubusercontent.com/9affb32750b17cd4b091cf47c56ad1a4014d33be/68747470733a2f2f692e6779617a6f2e636f6d2f39663138656162396466623132336439323861656366376461613365303164612e676966
)
I tried to make foldout by changing your boxGroup but not work

```
using UnityEditor;
using UnityEngine;

namespace NaughtyAttributes.Editor
{
    [PropertyGrouper(typeof(BoxGroupAttribute))]
    public class BoxGroupPropertyGrouper : PropertyGrouper
    {
        bool status = true;

        public override void BeginGroup(string label)
        {
            status = EditorGUILayout.Foldout(status,"Test");
            if(!status){
            return;
            }
        }

        public override void EndGroup()
        {
            EditorGUILayout.EndVertical();
            
        }
    }
}
```

**Comment by smkplus** [comment]
Hey please answer me I need this

**Comment by dbrizov** [comment]
There is a pull request for that #162, so I'll will close this, and leave the pull request only.
