### ISSUE TITLE
Error's after importing NA commit: 01c7443

### ISSUE THREAD

**Issue by thebspin** [dbrizov/NaughtyAttributes#6]
![Image of problem](https://i.imgur.com/iNQLBE2.png)

**Comment by dbrizov** [comment]
Hmm, that's strange. Can I ask what Unity version you are using?

**Comment by thebspin** [comment]
Yes sorry forgot too mention it, its still Unity 2017.1.0p4 on Windows 10. I downloaded the zip, moved the NaughtyAttributes to my plugins folder and got these errors.

**Comment by dbrizov** [comment]
Just fixed it mate. Thank you very much.
BTW you can download the NaughtyAttributes.unitypackage, it's always up to date
