### ISSUE TITLE
ShowIf will always show BoxGroup name

### ISSUE THREAD

**Issue by omid3098** [dbrizov/NaughtyAttributes#61]
``` C#
private bool MoveSelected() { return animationType == AnimationType.Move; }
[ShowIf("MoveSelected")] [BoxGroup("Move")] [SerializeField] Vector3 targetPosition;
```
we will always see BoxGroup title:

![image](https://user-images.githubusercontent.com/6388730/57568127-63811b80-73f8-11e9-8197-68f527e6cf7e.png)

**Comment by dbrizov** [comment]
Fixed in 18fa83e9fa7e3f20839452ee4dfce2d5877cc94f
