### ISSUE TITLE
[Request] ReorderableEvents

### ISSUE THREAD

**Issue by ChristophHoltmann** [dbrizov/NaughtyAttributes#70]
Great plugin! It is super useful and I like how easy it is to use!

I would like to see reorderable events, like reorderable lists.

**Comment by ChristophHoltmann** [comment]
It also would be great to have events where you can have enums as parameter

**Comment by dbrizov** [comment]
When you reorder something you want some events to be called? What should the signature of the event be?

**Comment by hairibar** [comment]
The way I'm reading it is they're talking about UnityEvents. They have an inspector similar to ReorderableLists, but you can't reorder the entries.

**Comment by dbrizov** [comment]
@hairibar 
Oh yeah, you are right. Thanks. I can make something like that :)

**Comment by ChristophHoltmann** [comment]
Yes @hairibar is right. That is what I meant.

Thank you @dbrizov! That would be perfect!

**Comment by dbrizov** [comment]
I found out that in debug script mode you can reorder the events. I think this is due to the fact that all lists in the inspector became reorderable since Unity **2020.2.x**
![image](https://user-images.githubusercontent.com/3619573/115982274-7750c880-a5a2-11eb-9804-e6b1fcdb8a8a.png)
