### ISSUE TITLE
Doesn't work with Odin installed

### ISSUE THREAD

**Issue by BenWoodford** [dbrizov/NaughtyAttributes#71]
This isn't necessarily a resolvable issue and probably isn't a big deal given you're unlikely to need to two in the same project, but if you have Odin in your project Naughty Attributes basically doesn't do anything.

Might just be worth mentioning it somewhere.

**Comment by JimmyCushnie** [comment]
Doesn't Odin provide its own implementations of all the functionality of NaughtAttributes?

**Comment by BenWoodford** [comment]
It does yeah. I generally prime my projects with a number of editor assets and had grabbed Odin on a sale (or bundle maybe?) but not really looked at it. That’s how I found out - I’d usually use NA but had started putting Odin in too and found out they silently conflict
