### ISSUE TITLE
[ISSUE] / [REQUEST] *Tag* Attribute for String array

### ISSUE THREAD

**Issue by ReGaSLZR** [dbrizov/NaughtyAttributes#81]
Hello, hello dev. 👋
Just wanted to ping ya that the *Tag* attribute does not work for string[] type. Dare I request a fix for this issue (if it is an issue) or a new attribute (*Tags* maybe?) to handle string[] types? 😀

**Comment by ReGaSLZR** [comment]
In the meantime, I found a solution for this scenario. Here's a link to anyone who might wanna check it out: http://www.brechtos.com/tagselectorattribute/

**Comment by dbrizov** [comment]
After Unity updated their UI in 2019.3, it started working, so I will be closing this one.
