### ISSUE TITLE
Copy paste bug in slider attribute = this.MaxValue = minValue;

### ISSUE THREAD

**Issue by MaZyGer** [dbrizov/NaughtyAttributes#84]
https://github.com/dbrizov/NaughtyAttributes/blob/b933f7e5698e7e57499f4b65839de18990d19f5b/Assets/NaughtyAttributes/Scripts/Core/DrawerAttributes/SliderAttribute.cs#L19

**Comment by dbrizov** [comment]
Oh, thanks. I will fix it when I get home

**Comment by dbrizov** [comment]
Already fixed some time ago, don't remember the revision
