### ISSUE TITLE
[Issue] Allow m_Script field exclusion custom editors

### ISSUE THREAD

**Issue by anton-kryvenko** [dbrizov/NaughtyAttributes#85]
There are cases when it's necessary to have custom editor for the object, but still use NaughtyAttributes for its fields. In this case inheriting from NaughtyAttributes.Editor.InspectorEditor instead of UnityEditor.Editor is an option.

Then it's possible to specify which fields to be drawn in a custom way by adding HideInInspector attribute. This will effectively hide them from drawing in base NaughtyAttributes.Editor.InspectorEditor class.

However there's a single field that can't be hidden this way - m_Script. So the idea is to make it possible somehow to exclude this field drawing from base class behavior.

**Comment by dbrizov** [comment]
Will not fix
