### ISSUE TITLE
Attributes not working in 2019.1.12f1

### ISSUE THREAD

**Issue by the-mr-matt** [dbrizov/NaughtyAttributes#87]
Just tried importing from the asset store and from here. Both are failing to display the property drawers. I made sure naughty attributes are placed in the "Plugins" folder, I added the namespace to my scripts, and I tried restarting.

Here is an example snippet:

```
using NaughtyAttributes;
using UnityEngine;

public class CenterOfMass : MonoBehaviour
{
    [Required] public GameObject test;
}
```

**Comment by the-mr-matt** [comment]
Update: I tried it in a fresh project and it worked. I also tried deleting all the solutions, library folder, and all the other generated stuff. Still didn't work.

FYI, my project also has VRTK and Steam VR. I doubt they would cause issues though.

**Comment by StyxOo** [comment]
I had the same issue. The solution was to remove my custom editor for that class. This obviously is not the best solution if you need advanced functionality in your custom editor. For me this wasn't an issue though.
