### ISSUE TITLE
Label/InfoBox with non-static access

### ISSUE THREAD

**Issue by Souk21** [dbrizov/NaughtyAttributes#9]
Hi! First I want to thank you for the awesome work, it's really useful as I prefer not to waste time with custom editors. Everything is working fine and as expected.

Would it be imaginable to add a "Label" attribute that could display non-static informations about the object? A quick example :

```
[Label]
private string MyLabelText 
{
    get { return transform.childCount + " childs."; }
}
```

I was thinking something with the same design than InfoBox.

Thank you !

**Comment by dbrizov** [comment]
I think I can make it. The problem with Properties is that I am limited to displaying only value types and string, because they aren't serialized, and the Unity Editor is pretty limited for non-serialized data.

**Comment by Souk21** [comment]
So it's not possible ?
I'm willing to try to do it, but I'm not certain how you deal with calling methods with strings. Are you using reflection ?
What I imagine should be doable with a logic similar to the OnValueChanged attribute (specifying a method/propriety to evaluate when showing in the inspector, but instead of returning a bool, the method returns a string that is in turn displayed in the inspector)

Thanks again

**Comment by dbrizov** [comment]
It is possible mate. I am actually doing it right now. I closed the issue in advance :D
I was a little busy these days, and didn't have the time to do it

**Comment by Souk21** [comment]
Oh, sweet! Thanks a lot 👍

**Comment by dbrizov** [comment]
Finished. I called it [ShowNativeProperty]
However, it's pretty limited. It can display only value types and string properties, because the EditorGUILayout class is very limited for non-serialized properties.
