### ISSUE TITLE
IMPROVEMENT: Add a collapsible flag to BoxGroup

### ISSUE THREAD

**Issue by AlexanderEvans** [dbrizov/NaughtyAttributes#92]
I had a feature request if it is reasonably feasible.  Could you add a flag for being able to expand and collapse boxgroups similar to how unity does this with structs in the inspector?  For instance something like `BoxGroup(true, "Component Refs") ` which would map to `BoxGroup(bool isCollapsible = false, string name = "")`  

Is something like this trivial, or is it actually really hard?  I know when I try to fiddle with the inspector stuff I run into a ton of issues with this stuff.  Regardless of if this get's implemented, as long as I'm submitting an Issue anyway, I want to thank you for creating this awesome asset.  Naughty Attributes has made customizing the editor so much easier for me.  Everyone should be using this asset, thanks for your work.

**Comment by dbrizov** [comment]
As @BLumbye mentioned, there is a pull request for a foldout group, so I will close this and leave the pull request only.
