### ISSUE TITLE
Improvements: Add [AssetOnly] / [SceneOnly] attributes, add [SceneAsset] attribute

### ISSUE THREAD

**Issue by subzero911** [dbrizov/NaughtyAttributes#93]
1) Add [AssetOnly] / [SceneOnly] attributes (as in Odin)
So if you have a slot in inspector is for a prefab, you can put only prefab from Project view there, and couldn't put a scene Gameobjects.
Conversely, if you have a slot for a scene objects only, you can't put assets from Project there.
2) Add serialization for Scene asset.
I want to have an ability to put a Scene in a slot. So I can load scene not by name but by scene asset reference directly.

**Comment by dbrizov** [comment]
There is already a pull request for this feature: #111
