### ISSUE TITLE
IMPROVEMENT: Convert repo to support UPM via manifest

### ISSUE THREAD

**Issue by AlexanderEvans** [dbrizov/NaughtyAttributes#94]
Can you please convert this asset to function with unity's new git supported package manager? Similar to what one line has done for their installation? Example: https://github.com/slavniyteo/one-line  This would make installation a lot easier on our club if we just had to clone down the manifest with the package dependencies.

**Comment by JimmyCushnie** [comment]
I made a pull request for this months ago (#62), but @dbrizov doesn't seemed to have looked at it yet.

**Comment by dbrizov** [comment]
Just did. Thank you very much @JimmyCushnie 

```
"com.dbrizov.naughtyattributes": "https://github.com/dbrizov/NaughtyAttributes.git#upm"
```
