### ISSUE TITLE
Dumb Question, but...

### ISSUE THREAD

**Issue by TheCodeDragon** [dbrizov/NaughtyAttributes#95]
How would I add this to my project? Assume idiot levels of understanding with me. My initial assumption is to just, download the zip, then copy the files into said project?

**Comment by JimmyCushnie** [comment]
Everything in the Assets folder goes in your project's Assets folder.

**Comment by TheCodeDragon** [comment]
And this is why dumb questions need to be asked sometimes. 
Thanks!
