### ISSUE TITLE
Improvement: Accept properties in "Dropdown" attribute

### ISSUE THREAD

**Issue by overdub** [dbrizov/NaughtyAttributes#99]
Every time I use the dropdown attribute I get to the point where I want to display dynamic content, like names of children or scene names. If Dropdown would accept properties (getters) or methods this would be easy.

Thanks for your great work!

**Comment by SanielX** [comment]
https://github.com/dbrizov/NaughtyAttributes/pull/55

There is pull request just for you I guess.

**Comment by dbrizov** [comment]
Implemented in version 2.0.0

**Comment by dbrizov** [comment]
Implemented in version 2.0.0
